=== victorrbravo/gestioninterna/gestioninterna/.safet/dtd/yawlworkflow.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : yawlworkflow.dtd
    Created on : 22 de enero de 2008, 15:46
    Author     : vbravo
    Description:
        Una definicion para gestionar archivos de flujos de trabajo (workflow)
        con el lenguaje YAWL (Yet Another Workflow Language) 
        http://www.yawl-system.com dentro del proyecto SAFET :
        Sistema Automatizado para Firma Electronica y Estampillado de Tiempo

    TODO define vocabulary identification data
    PUBLIC ID  : -//vendor//vocabulary//EN
    SYSTEM ID  : http://server/path/yawlworkflow.dtd
-->

<!-- TODO define your own vocabulary/syntax. Example follows:  -->
<!ELEMENT yawl (workflow,configuration*)>
<!ATTLIST yawl
version  CDATA #REQUIRED> <!-- must be "0.01"> -->
<!ELEMENT workflow (token,(task|compositetask|variable|condition|parameter)*)>
<!ELEMENT token (#PCDATA) >
<!ATTLIST token     key CDATA #REQUIRED                    
                    description CDATA #IMPLIED
                    type (sql|file|webpage) "sql"
                    config CDATA #IMPLIED
                    keysource CDATA #REQUIRED>
<!ELEMENT configuration (#PCDATA) >
<!ATTLIST configuration  id CDATA #REQUIRED
                         connectstring CDATA #REQUIRED>
<!ATTLIST workflow  id CDATA #REQUIRED
                    desc CDATA #IMPLIED>
<!ELEMENT task (variable|port|autofilter|recursivefilter)*>
<!ATTLIST task id CDATA #REQUIRED 
               title  CDATA #IMPLIED
               hideuntil  CDATA #IMPLIED
               numericinfo  CDATA #IMPLIED
               textualinfo  CDATA #IMPLIED
	       left CDATA #IMPLIED
	       top CDATA #IMPLIED
	       role CDATA #IMPLIED
	       note CDATA #IMPLIED
               multiplicity (unique|multiple) "unique"
          type (atomic|composite) "atomic"
          report (yes|no) "no"  >
<!ELEMENT compositetask (workflow)>
<!ELEMENT variable (document*)>
<!ATTLIST variable  id CDATA #REQUIRED 
                    tokenlink CDATA #IMPLIED
                    description CDATA #IMPLIED
                    scope (net|task) "net"
                    type (sql|file|webpage) "sql"
                    usage (input|output|inout) "input"
                    config CDATA #IMPLIED
                    source CDATA #IMPLIED
                    rolfield CDATA #IMPLIED
                    timestampfield CDATA #IMPLIED
		    left CDATA #IMPLIED
		    top CDATA #IMPLIED
		    groupby CDATA #IMPLIED
                    documentsource CDATA #REQUIRED>
<!ELEMENT document (#PCDATA)  >
<!ATTLIST document  key CDATA #REQUIRED>
<!ELEMENT connection (#PCDATA) >
<!ATTLIST connection source  CDATA #IMPLIED
		     query CDATA #IMPLIED
		     options CDATA #IMPLIED
		     left CDATA #IMPLIED
		     top CDATA #IMPLIED
		     back CDATA #IMPLIED
		     tokenlink CDATA #IMPLIED>					 
<!ELEMENT port (connection*) >
<!ELEMENT autofilter (#PCDATA) >
<!ATTLIST autofilter id CDATA #REQUIRED 
		side (bottom|down|up|forward) "forward"
	       source  CDATA #REQUIRED
               type (join|split)  #REQUIRED
               query  CDATA #REQUIRED
               subquery  CDATA #IMPLIED
               options  CDATA #IMPLIED		
               tokenlink  CDATA #IMPLIED
               pattern (none|and|or|xor) "or"	       
               report (yes|no) "no"
               subreport (yes|no) "no"
		>
<!ELEMENT recursivefilter (#PCDATA) >
<!ATTLIST recursivefilter id CDATA #REQUIRED 
		side (bottom|down|up|forward) "forward"
	       source  CDATA #REQUIRED
               type (join|split)  #REQUIRED
               query  CDATA #REQUIRED
               options  CDATA #IMPLIED		
               tokenlink  CDATA #IMPLIED
               pattern (none|and|or|xor) "or"
	       initial CDATA #REQUIRED
	       filter CDATA #REQUIRED
               report (yes|no) "no"  
	       onlyfathers (yes|no) "no" >

<!ATTLIST port side (bottom|down|up|forward) #REQUIRED
               type (join|split)  #REQUIRED
               query  CDATA #IMPLIED
               tokenlink  CDATA #IMPLIED
               options  CDATA #IMPLIED
               drop    CDATA #IMPLIED  
	       config CDATA #IMPLIED
               pattern (none|and|or|xor) "none">
<!ELEMENT condition (port+) >
<!ATTLIST condition id CDATA #REQUIRED
               numericinfo  CDATA #IMPLIED
               textualinfo  CDATA #IMPLIED 
	       left CDATA #IMPLIED
	       top CDATA #IMPLIED
               type (start|end|inprocess) "inprocess"
            report (yes|no) "no"  >
<!ELEMENT taskid (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT link (#PCDATA)>
<!ELEMENT source (#PCDATA)>
<!ELEMENT connectstring (#PCDATA)>
<!ELEMENT parameter (#PCDATA)  >
<!ATTLIST parameter	type CDATA #IMPLIED   
			mandatory CDATA #IMPLIED
			title CDATA #IMPLIED
			primarykey (yes|no) "no"
			validation CDATA #IMPLIED 
			options CDATA #IMPLIED
			function CDATA #IMPLIED 
			format (time_t|integer) "time_t" 
			desc CDATA #IMPLIED
			literal CDATA #IMPLIED
			sequence CDATA #IMPLIED
			typesequence (next|current) "next"
			input CDATA #IMPLIED
			path CDATA #IMPLIED
			visible CDATA #IMPLIED
 			order (asc|desc|none) "asc" 
			icon CDATA #IMPLIED
			index CDATA #IMPLIED  
			filter CDATA #IMPLIED 
			repetible (yes|no) "no"
			configurekey CDATA #IMPLIED 
			defaultvalue CDATA #IMPLIED >

=== victorrbravo/gestioninterna/gestioninterna/.safet/flowfiles/estado_publicaciones.xml
<!DOCTYPE yawl SYSTEM 'file:///home/vbravo/.safet/dtd/yawlworkflow.dtd'>
<!--
Documento  : tickets.xml
Creado     : 16/10/08 09:27 AM
Autor      : nombre_autor
Descripcion: Archivo generado por plantilla de la Libreria SAFET
-->
<!--<!DOCTYPE yawl SYSTEM "http://trac-safet.cenditel.gob.ve/dtd/yawlworkflow.dtd">-->
<yawl version="0.01">
 <workflow id="estado_publicaciones">
  <token keysource="vacaciones" key="id"/>
  <parameter title="Textualinfo" options="" type="string" mandatory="no"/>
  <parameter title="Paralelo al nodo siguiente" options="No::No::No,Si::Si::Si" type="combolistliteral" mandatory="no"/>
  <condition type="start" id="inicial">
   <port side="forward" type="split">
     <connection query="select status from vacaciones" options="iniciado" 
source="Borrador"/>
   </port>
  </condition>
  <task title="" id="Borrador" textualinfo="">
   <port side="forward" type="split" >
    <connection query="select status from vacaciones" options="TalentoHumano" source="TalentoHumano"/>
   </port>
   <variable config="1" documentsource="select  id,status from vacaciones" groupby="order by id desc" type="sql" tokenlink="" id="viniciado" rolfield="" scope="task" timestampfield=""/>
  </task>
  <task title="" id="TalentoHumano" textualinfo="">
   <port  side="forward" type="split" pattern="none" >
    <connection query="select status from vacaciones" options="iniciado" back="yes"  source="Borrador"/>    
     <connection query="select status from vacaciones" options="DireccionEjecutiva" source="DireccionEjectiva"/>
    
   </port>
   <variable config="1" documentsource="select  id,status from vacaciones" groupby="order by id desc" type="sql" tokenlink="" id="vTalentoHumano" rolfield="" scope="task" timestampfield=""/>
  </task>
  
  <task title="" id="DireccionEjectiva" textualinfo="" report="yes">
   <port side="bottom" type="split" pattern="none" >
        <connection query="select status from vacaciones" options="Presidencia" source="Entregado"/>     
   </port>
   <variable config="1" documentsource="select  idi,status from vacaciones" groupby="order by id desc" type="sql" tokenlink="" id="vDireccionEjecutiva" rolfield="" scope="task" timestampfield=""/>
  </task>
  <task title="" id="Entregado" textualinfo="">
   <port side="forward" type="split" pattern="or" >
     <connection query="select status from vacaciones" options="iniciado" back="yes"  source="Borrador"/>
    <connection query="true" options="" source="final"/>
   </port>
   <variable config="1" documentsource="select  id,status from vacaciones" groupby="order by id desc" type="sql" tokenlink="" id="vPresidencia" rolfield="" scope="task" timestampfield=""/>
  </task>
  <condition id="final">
   <port side="forward" type="split">
    <connection source=""/>
   </port>
  </condition>
 </workflow>
 <configuration id="1" connectstring="psql:seguridad.cenditel.gob.ve:ticket:vbravo:vbravo_"/>
</yawl>

=== victorrbravo/gestioninterna/gestioninterna/.safet/flowfiles/ReporteDetallesConvenioActivoOperadora.xml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE yawl SYSTEM 'file:///home/c30/.safet/dtd/yawlworkflow.dtd'>
<!--
Documento  : ConvenioOperadora.xml
Creado     : 27/10/2015 09:27 AM
Autor      : Josè Sulbaràn
Descripcion: Archivo generado por plantilla de la Libreria SAFET
-->


<yawl version="0.01">
 <workflow id="operadora_recaudacion">
<token keysource="operadora_operadora" key="razon_social"/>
 
  <!-- ################################################# -->

  <condition type="start" id="inicial">
   <port side="forward" type="split">
   <connection query=" select usuario_operadora_id from operadora_operadora" options=">0" source="Operadora"
      tokenlink=""/>
   </port>
  </condition>
  
  <!-- ################################################ -->

  <task title="" id="Operadora"> 
   <port side="forward" type="split" >
         
   <connection query=" select operadora_convenio.pagado from operadora_operadora" options="false" source="Detalle" tokenlink="[usuario_operadora_id,operadora_id:operadora_declaracion][convenio_id,id:operadora_convenio]"/>

   </port>

  <variable config="1" documentsource="select usuario_operadora_id from operadora_operadora"
    type="sql" tokenlink=""  id="vOperadora" rolfield="" scope="task" timestampfield=""/>
  </task>

 <!-- ################################################### -->

<task title="" id="Detalle"> 
   <port side="forward" type="split">
         
      <connection query="true" options="" source="final"/>  
   </port>
   
  <variable config="1" documentsource="select distinct rif, operadora_convenio.numero, operadora_convenio.fecha,
  operadora_convenio.fecha_firma, operadora_convenio.tributo_adeudado, operadora_convenio.multas,
  operadora_convenio.intereses_moratorios,operadora_convenio.monto_fianza,operadora_convenio.monto_total,
  operadora_convenio.monto_cuota,operadora_convenio.num_cuotas,operadora_convenio.tasa_anual,operadora_convenio.pagado from operadora_operadora" 
    type="sql" tokenlink="[usuario_operadora_id,operadora_id:operadora_declaracion][convenio_id,id:operadora_convenio]"  id="vDetalle" rolfield="" scope="task" timestampfield=""/>
  </task>

 <!-- ################################################### -->



  <condition id="final">
   <port side="forward" type="split">
    <connection source=""/>
   </port>
  </condition>
  
 </workflow>
 <configuration id="1" connectstring="psql:seguridad.cenditel.gob.ve:ticket:vbravo:vbravo_"/>
</yawl>

=== victorrbravo/gestioninterna/gestioninterna/.safet/flowfiles/SolicitudVistaVacacionesGraph.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--
Documento  : tickets.xml
Creado     : 16/10/08 09:27 AM
Autor      : nombre_autor
Descripcion: Archivo generado por plantilla de la Libreria SAFET
-->

<!--<!DOCTYPE yawl SYSTEM "http://trac-safet.cenditel.gob.ve/dtd/yawlworkflow.dtd">-->
<!DOCTYPE yawl SYSTEM "file:///home/vbravo/.safet/dtd/yawlworkflow.dtd">
<yawl  version="0.01">
<workflow id="Generar planilla de solicitud de vista_vacaciones" desc="Planilla que se generar con los datos de una solicitud de vista_vacaciones">
<token key="id"  keysource="vista_vacaciones">
</token>
<parameter type="string" options="" mandatory="no"
                       title="Mostrar_en_grafico" configurekey="Plugins.Graphviz/plugins.graphviz.extrainfo.show" defaultvalue="InfoText,InfoDate" >
</parameter>
 <parameter type="string" options="" mandatory="no"
                       title="Mostrar_tipo_fecha" configurekey="Result/result.dates.human" defaultvalue="HumanDetail" >
</parameter>
    
<condition id="inicial" type="start">
	<port side="forward" type="split"  >
		<connection   source="Iniciado" query="select status from vista_vacaciones"  options="iniciado" tokenlink="" >
		</connection>
	</port>
</condition>

<task id="Iniciado"  title="todas" >
	<port side="forward" type="split"  >
		<connection   source="TalentoHumano" query="select status from vista_vacaciones"  options="Talento_humano" tokenlink="" >
		</connection>

	</port>
	 <variable id="vSolicitud" scope="task"  type="sql" config="1"   tokenlink="" 
                documentsource="select id,id_cedula from vista_vacaciones"
 
rolfield="(select nombre_periodo from vacaciones_registro where vacaciones_registro.id_vacaciones=vista_vacaciones.id and vacaciones_registro.status='iniciado' limit 1)"  
timestampfield="(select fecha_accion from vacaciones_registro where vacaciones_registro.id_vacaciones=vista_vacaciones.id and vacaciones_registro.status='iniciado' limit 1)" 

>
     </variable>
</task>
<task id="TalentoHumano"  title="todas" >
	<port side="forward" type="split" pattern="or" >
		<connection   source="DireccionEjecutiva" query="select status from vista_vacaciones"  options="DireccionEjecutiva" tokenlink="" >
		</connection>
		<connection   source="Iniciado" query="select status from vista_vacaciones"  options="iniciado" tokenlink="" back="yes" >
		</connection>

	</port>
	 <variable id="vTalentoHumano" scope="task"  type="sql" config="1"   tokenlink="" 
                documentsource="select id,id_cedula from vista_vacaciones"
 
rolfield="(select nombre_periodo from vacaciones_registro where vacaciones_registro.id_vacaciones=vista_vacaciones.id and vacaciones_registro.status='Talento_humano' limit 1)"  
timestampfield="(select fecha_accion from vacaciones_registro where vacaciones_registro.id_vacaciones=vista_vacaciones.id and vacaciones_registro.status='Talento_humano' limit 1)" 

 >
     </variable>
</task>

<task id="DireccionEjecutiva"  title="Planilla vista_vacaciones" >
	<port side="forward" type="split"  >
	    <connection source="Presidencia" query="select status from vista_vacaciones" options="Presidencia" >
        </connection>
	</port>
	 <variable id="vDireccionEjecutiva" scope="task"  type="sql" config="1"   tokenlink=""
                 documentsource="select id,id_cedula from vista_vacaciones"
rolfield="(select nombre_periodo from vacaciones_registro where vacaciones_registro.id_vacaciones=vista_vacaciones.id and vacaciones_registro.status='DireccionEjecutiva' limit 1)"  
timestampfield="(select fecha_accion from vacaciones_registro where vacaciones_registro.id_vacaciones=vista_vacaciones.id and vacaciones_registro.status='DireccionEjecutiva' limit 1)" 

 >
     </variable>
</task>
<task id="Presidencia"  title="Aprobacion del Presidente" >
	<port side="forward" type="split" pattern="none" >
		<connection source="Archivar_solicitud_procesada" query="select status from vista_vacaciones" options="Archivar_solicitud_procesada" tokenlink="" >

		</connection>
	</port>
	 <variable id="vPresidencia" scope="task"  type="sql" config="1"   tokenlink=""
                 documentsource="select id,id_cedula, nombreapellido from vista_vacaciones"
rolfield="(select nombre_periodo from vacaciones_registro where vacaciones_registro.id_vacaciones=vista_vacaciones.id and vacaciones_registro.status='Presidencia' limit 1)"  
timestampfield="(select fecha_accion from vacaciones_registro where vacaciones_registro.id_vacaciones=vista_vacaciones.id and vacaciones_registro.status='Presidencia' limit 1)" 

 >
     </variable>
</task>
<task id="Archivar_solicitud_procesada"  title="solicitud_archivada" >
	<port side="forward" type="split"  >
		<connection source="final" query="true" options="" tokenlink="" >

		</connection>

	</port>
	 <variable id="vArchivar" scope="task"  type="sql" config="1"   tokenlink=""
                 documentsource="select id,id_cedula from vista_vacaciones"
 rolfield=""  timestampfield="" 
 >
     </variable>
</task>
<condition id="final">
	<port side="forward" type="split">
		<connection source="">
		</connection>
	</port>
</condition>
</workflow>
	<configuration id="1" connectstring="psql:seguridad.cenditel.gob.ve:ticket:vbravo:vbravo_">
	</configuration>
</yawl>

=== victorrbravo/gestioninterna/gestioninterna/.safet/flowfiles/RecaudacionOperadoraEspecificoRif.xml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE yawl SYSTEM 'file:///home/c30/.safet/dtd/yawlworkflow.dtd'>
<!--
Documento  : RecaudacionOperadora.xml
Creado     : 27/10/2015 09:27 AM
Autor      : Ing. Josè Sulbaràn
Descripcion: Archivo generado por plantilla de la Libreria SAFET
-->

<yawl version="0.01">
 <workflow id="operadora_operadora">
<token keysource="operadora_operadora" key="usuario_operadora_id"/>



<parameter title="Anho" options="" type="string" mandatory="no"/>
 <parameter title="Periodo" options="" type="string" mandatory="no"/>
 <parameter title="Rif" options="" type="string" mandatory="no"/>

<!-- ##############################################################################-->

  <condition type="start" id="inicial">
   <port side="forward" type="split">
   <connection query=" select usuario_operadora_id from operadora_operadora" options=">0" source="Operadoras"
      tokenlink=""/>

   </port>
  </condition>
   

<!-- ##############################################################################-->  


  <task title="Generales" id="Operadoras">
   <port side="forward" type="split">
    
    <connection
       query="select rif from operadora_operadora" options="{#Rif}"  source="Rif_De_Busqueda"
       tokenlink=""/>
       
   </port>

   <variable config="1" documentsource="select razon_social from operadora_operadora" type="sql" 
    tokenlink="" 
    id="vOperadoras" rolfield="" scope="task"
    timestampfield=""/>

  </task>

<!-- ##############################################################################-->

  <task title="{#Rif}" id="Rif_De_Busqueda">
   <port side="forward" type="split">
    
    <connection
       query="select  operadora_recaudacion.anho from operadora_operadora" options="{#Anho}"  source="Anho"
       tokenlink="[usuario_operadora_id,operadora_id:operadora_declaracion][recaudacion_id,id:operadora_recaudacion]"/>
       

   </port>
   <variable config="1" documentsource="select razon_social from operadora_operadora" type="sql" 
    tokenlink="" 
    id="vOperadora_De_Busqueda" rolfield="" scope="task"
    timestampfield=""/>

  </task>

 <!-- ##############################################################################-->

  <task title="::safethide::" id="Anho"> 
   <port side="forward" type="split" >
    
     <connection query=" select operadora_recaudacion.num_periodo from operadora_operadora" options="{#Periodo}" source="Declarada"
      tokenlink="[usuario_operadora_id,operadora_id:operadora_declaracion][recaudacion_id,id:operadora_recaudacion]"/>
     
   </port>

  <variable config="1" documentsource="select razon_social, operadora_recaudacion.id from operadora_operadora" type="sql" 
    tokenlink="[usuario_operadora_id,operadora_id:operadora_declaracion][recaudacion_id,id:operadora_recaudacion]" 
    id="vAnho" rolfield="" scope="task"
    timestampfield=""/>
 
  </task>


<!-- ##############################################################################-->
  

   <task title="Operadora a declarado" id="Declarada"> 
   <port side="forward" type="split" pattern="or" >
    

     <connection query="select operadora_pago.estatus_pago_id from operadora_operadora" options="1"
       source="Pago_en_Revision" tokenlink="[usuario_operadora_id,operadora_id:operadora_declaracion][recaudacion_id,id:operadora_recaudacion][id,declaracion_id:operadora_detallepago][pago_id,id:operadora_pago]"/>
 
  <connection query=" select operadora_declaracion.moroso from operadora_operadora" options="true" source="Moroso"
      tokenlink="[usuario_operadora_id,operadora_id:operadora_declaracion]"/>
  
        
 
   </port>

  <variable config="1" documentsource="select  operadora_declaracion.id, razon_social, operadora_declaracion.operadora_id, operadora_declaracion.recaudacion_id,  operadora_recaudacion.anho, operadora_recaudacion.num_periodo from operadora_operadora " type="sql" 
    tokenlink="[usuario_operadora_id,operadora_id:operadora_declaracion]" 
    id="vDeclarada" rolfield="" scope="task"
    timestampfield=""/>
 
  </task>

 


<!-- ##############################################################################-->  

<task title="Mora de la operadora" id="Moroso">
   <port side="forward" type="split">

<connection query=" select operadora_declaracion.convenio_id from operadora_operadora" options=">0" source="Convenio"
      tokenlink="[usuario_operadora_id,operadora_id:operadora_declaracion]"/>
 
         
   </port>
   <variable config="1" documentsource="select razon_social, operadora_declaracion.operadora_id, operadora_declaracion.moroso from operadora_operadora" type="sql" 
    tokenlink="[usuario_operadora_id,operadora_id:operadora_declaracion]" 
    id="vMoroso" rolfield="" scope="task"
    timestampfield=""/>

  </task>

  <!-- ##############################################################################-->  

<task title="Convenios de la operadora" id="Convenio">
   <port side="forward" type="split">
          
     <connection query="select operadora_pago.estatus_pago_id from operadora_operadora" options="1"
       source="Pago_en_Revision" tokenlink="[usuario_operadora_id,operadora_id:operadora_declaracion][recaudacion_id,id:operadora_recaudacion][id,declaracion_id:operadora_detallepago][pago_id,id:operadora_pago]"/>
 
         
   </port>
   <variable config="1" documentsource="select  operadora_declaracion.convenio_id, razon_social, operadora_declaracion.operadora_id, operadora_declaracion.id from operadora_operadora" type="sql" 
    tokenlink="[usuario_operadora_id,operadora_id:operadora_declaracion]" 
    id="vConvenio" rolfield="" scope="task"
    timestampfield=""/>

  </task>



<!-- ##############################################################################-->  

  <task title="Operadora esta en estado de revision" id="Pago_en_Revision">
   <port side="forward" type="split">
    
     <connection query="select operadora_pago.estatus_pago_id from operadora_operadora" options="2"
       source="Pago_Revisado" tokenlink="[usuario_operadora_id,operadora_id:operadora_declaracion][recaudacion_id,id:operadora_recaudacion][id,declaracion_id:operadora_detallepago][pago_id,id:operadora_pago]"/>



   </port>
   <variable config="1" documentsource="select razon_social from operadora_operadora" type="sql" 
    tokenlink="[usuario_operadora_id,operadora_id:operadora_declaracion][recaudacion_id,id:operadora_recaudacion][id,declaracion_id:operadora_detallepago][pago_id,id:operadora_pago]" 
    id="Pago_en_Revision" rolfield="" scope="task"
    timestampfield=""/>

  </task>

  
  <!-- ##############################################################################-->  

  <task title="Operadora esta en estado revisado" id="Pago_Revisado">
   <port side="forward" type="split">
    
 <connection query="select operadora_declaracion.pagado from operadora_operadora" options="true"
       source="Pago" tokenlink="[usuario_operadora_id,operadora_id:operadora_declaracion]"/>

          
   </port>
   <variable config="1" documentsource="select razon_social, operadora_recaudacion.id,operadora_recaudacion.anho, operadora_recaudacion.num_periodo, operadora_declaracion.recaudacion_id, operadora_declaracion.id, operadora_detallepago.declaracion_id, operadora_detallepago.id,  operadora_pago.id, operadora_pago.estatus_pago_id from operadora_operadora" type="sql" 
    tokenlink="[usuario_operadora_id,operadora_id:operadora_declaracion][recaudacion_id,id:operadora_recaudacion][id,declaracion_id:operadora_detallepago][pago_id,id:operadora_pago]" 
    id="Pago_Revisado" rolfield="" scope="task"
    timestampfield=""/>

  </task>
  
  
<!-- ##############################################################################-->  


  <task title="Pago de la operadora" id="Pago">
   <port side="forward" type="split">
    
        <connection query="true" options="" source="final"/>     

   </port>
   <variable config="1" documentsource="select razon_social from operadora_operadora" type="sql" 
    tokenlink="[usuario_operadora_id,operadora_id:operadora_declaracion]" 
    id="Pago" rolfield="" scope="task"
    timestampfield=""/>

  </task>




<!-- ##############################################################################-->  


  <condition id="final">
   <port side="forward" type="split">
    <connection source=""/>
   </port>
  </condition>
  


 </workflow>
 <configuration id="1" connectstring="psql:seguridad.cenditel.gob.ve:ticket:vbravo:vbravo_"/>
</yawl>

=== victorrbravo/gestioninterna/gestioninterna/.safet/flowfiles/ReportePorEstadoMoroso.xml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE yawl SYSTEM 'file:///home/c30/.safet/dtd/yawlworkflow.dtd'>
<!--
Documento  : ConvenioOperadora.xml
Creado     : 27/10/2015 09:27 AM
Autor      : Josè Sulbaràn
Descripcion: Archivo generado por plantilla de la Libreria SAFET
-->


<yawl version="0.01">
 <workflow id="operadora_declaracion">
<token keysource="operadora_operadora" key="razon_social"/>
  
 <parameter title="Id"  type="string" mandatory="si"/>

  <!-- ################################################# -->

  <condition type="start" id="inicial">
   <port side="forward" type="split">
   <connection query=" select usuario_operadora_id from operadora_operadora" options="{#Id}" source="Operadora"
      tokenlink=""/>
   </port>
  </condition>
  

  <!-- ################################################ -->

  <task title="" id="Operadora"> 
   <port side="forward" type="split">
    
   
    <connection query=" select operadora_declaracion.moroso from operadora_operadora" options="true" source="Moroso"
      tokenlink="[usuario_operadora_id,operadora_id:operadora_declaracion][recaudacion_id,id:operadora_recaudacion]"/>


   </port>

  <variable config="1" documentsource="select rif from operadora_operadora" 
    type="sql" tokenlink=""  id="vOperadora" rolfield="" scope="task" timestampfield=""/>
  </task>

  <!-- ################################################ -->

  
  <task title="" id="Moroso"> 
   <port side="forward" type="split">
    
   <connection query="true" options="" source="final"/>
     
   </port>

  <variable config="1" documentsource="select distinct operadora_recaudacion.num_periodo from operadora_operadora" type="sql" 
    tokenlink="[usuario_operadora_id,operadora_id:operadora_declaracion][recaudacion_id,id:operadora_recaudacion]" 
    id="vMoroso" rolfield="" scope="task"
    timestampfield="" groupby= "order by num_periodo"/>
  </task>

  <!-- ################################################ -->

  <condition id="final">
   <port side="forward" type="split">
    <connection source=""/>
   </port>
  </condition>

  
 </workflow>
 <configuration id="1" connectstring="psql:seguridad.cenditel.gob.ve:ticket:vbravo:vbravo_"/>
</yawl>
