=== victorrbravo/gestioninterna/gestioninterna/.safet/dtd/yawlworkflow.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : yawlworkflow.dtd
    Created on : 22 de enero de 2008, 15:46
    Author     : vbravo
    Description:
        Una definicion para gestionar archivos de flujos de trabajo (workflow)
        con el lenguaje YAWL (Yet Another Workflow Language) 
        http://www.yawl-system.com dentro del proyecto SAFET :
        Sistema Automatizado para Firma Electronica y Estampillado de Tiempo

    TODO define vocabulary identification data
    PUBLIC ID  : -//vendor//vocabulary//EN
    SYSTEM ID  : http://server/path/yawlworkflow.dtd
-->

<!-- TODO define your own vocabulary/syntax. Example follows:  -->
<!ELEMENT yawl (workflow,configuration*)>
<!ATTLIST yawl
version  CDATA #REQUIRED> <!-- must be "0.01"> -->
<!ELEMENT workflow (token,(task|compositetask|variable|condition|parameter)*)>
<!ELEMENT token (#PCDATA) >
<!ATTLIST token     key CDATA #REQUIRED                    
                    description CDATA #IMPLIED
                    type (sql|file|webpage) "sql"
                    config CDATA #IMPLIED
                    keysource CDATA #REQUIRED>
<!ELEMENT configuration (#PCDATA) >
<!ATTLIST configuration  id CDATA #REQUIRED
                         connectstring CDATA #REQUIRED>
<!ATTLIST workflow  id CDATA #REQUIRED
                    desc CDATA #IMPLIED>
<!ELEMENT task (variable|port|autofilter|recursivefilter)*>
<!ATTLIST task id CDATA #REQUIRED 
               title  CDATA #IMPLIED
               hideuntil  CDATA #IMPLIED
               numericinfo  CDATA #IMPLIED
               textualinfo  CDATA #IMPLIED
	       left CDATA #IMPLIED
	       top CDATA #IMPLIED
	       role CDATA #IMPLIED
	       note CDATA #IMPLIED
               multiplicity (unique|multiple) "unique"
          type (atomic|composite) "atomic"
          report (yes|no) "no"  >
<!ELEMENT compositetask (workflow)>
<!ELEMENT variable (document*)>
<!ATTLIST variable  id CDATA #REQUIRED 
                    tokenlink CDATA #IMPLIED
                    description CDATA #IMPLIED
                    scope (net|task) "net"
                    type (sql|file|webpage) "sql"
                    usage (input|output|inout) "input"
                    config CDATA #IMPLIED
                    source CDATA #IMPLIED
                    rolfield CDATA #IMPLIED
                    timestampfield CDATA #IMPLIED
		    left CDATA #IMPLIED
		    top CDATA #IMPLIED
		    groupby CDATA #IMPLIED
                    documentsource CDATA #REQUIRED>
<!ELEMENT document (#PCDATA)  >
<!ATTLIST document  key CDATA #REQUIRED>
<!ELEMENT connection (#PCDATA) >
<!ATTLIST connection source  CDATA #IMPLIED
		     query CDATA #IMPLIED
		     options CDATA #IMPLIED
		     left CDATA #IMPLIED
		     top CDATA #IMPLIED
		     back CDATA #IMPLIED
		     tokenlink CDATA #IMPLIED>					 
<!ELEMENT port (connection*) >
<!ELEMENT autofilter (#PCDATA) >
<!ATTLIST autofilter id CDATA #REQUIRED 
		side (bottom|down|up|forward) "forward"
	       source  CDATA #REQUIRED
               type (join|split)  #REQUIRED
               query  CDATA #REQUIRED
               subquery  CDATA #IMPLIED
               options  CDATA #IMPLIED		
               tokenlink  CDATA #IMPLIED
               pattern (none|and|or|xor) "or"	       
               report (yes|no) "no"
               subreport (yes|no) "no"
		>
<!ELEMENT recursivefilter (#PCDATA) >
<!ATTLIST recursivefilter id CDATA #REQUIRED 
		side (bottom|down|up|forward) "forward"
	       source  CDATA #REQUIRED
               type (join|split)  #REQUIRED
               query  CDATA #REQUIRED
               options  CDATA #IMPLIED		
               tokenlink  CDATA #IMPLIED
               pattern (none|and|or|xor) "or"
	       initial CDATA #REQUIRED
	       filter CDATA #REQUIRED
               report (yes|no) "no"  
	       onlyfathers (yes|no) "no" >

<!ATTLIST port side (bottom|down|up|forward) #REQUIRED
               type (join|split)  #REQUIRED
               query  CDATA #IMPLIED
               tokenlink  CDATA #IMPLIED
               options  CDATA #IMPLIED
               drop    CDATA #IMPLIED  
	       config CDATA #IMPLIED
               pattern (none|and|or|xor) "none">
<!ELEMENT condition (port+) >
<!ATTLIST condition id CDATA #REQUIRED
               numericinfo  CDATA #IMPLIED
               textualinfo  CDATA #IMPLIED 
	       left CDATA #IMPLIED
	       top CDATA #IMPLIED
               type (start|end|inprocess) "inprocess"
            report (yes|no) "no"  >
<!ELEMENT taskid (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT link (#PCDATA)>
<!ELEMENT source (#PCDATA)>
<!ELEMENT connectstring (#PCDATA)>
<!ELEMENT parameter (#PCDATA)  >
<!ATTLIST parameter	type CDATA #IMPLIED   
			mandatory CDATA #IMPLIED
			title CDATA #IMPLIED
			primarykey (yes|no) "no"
			validation CDATA #IMPLIED 
			options CDATA #IMPLIED
			function CDATA #IMPLIED 
			format (time_t|integer) "time_t" 
			desc CDATA #IMPLIED
			literal CDATA #IMPLIED
			sequence CDATA #IMPLIED
			typesequence (next|current) "next"
			input CDATA #IMPLIED
			path CDATA #IMPLIED
			visible CDATA #IMPLIED
 			order (asc|desc|none) "asc" 
			icon CDATA #IMPLIED
			index CDATA #IMPLIED  
			filter CDATA #IMPLIED 
			repetible (yes|no) "no"
			configurekey CDATA #IMPLIED 
			defaultvalue CDATA #IMPLIED >

=== victorrbravo/gestioninterna/gestioninterna/.safet/flowfiles/flujofirmado.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--
Documento  : tickets.xml
Creado     : 16/10/08 09:27 AM
Autor      : nombre_autor
Descripcion: Archivo generado por plantilla de la Libreria SAFET
-->

<!--<!DOCTYPE yawl SYSTEM "http://trac-safet.cenditel.gob.ve/dtd/yawlworkflow.dtd">-->
<!DOCTYPE yawl SYSTEM "file:///home/debian/.safet/dtd/yawlworkflow.dtd">
<yawl  version="0.01">
<workflow id="TicketsTrac" desc="Tickets usados por Trac">
	<token key="id"  keysource="ticket">
	</token>
<condition id="inicial" type="start">
                <port side="forward" type="split"   >
                        <connection   source="Nuevo" query="select status from ticket"  options="new" tokenlink="">
			</connection>
		</port>
	</condition>
	<task id="Nuevo"  title="en atencion" >
                <port side="forward" type="split"  pattern="or" >
                        <connection source="Aceptado" query="select status from ticket" options="accepted" >
			</connection>

                        <connection source="FaltaInfo" query="select status from ticket" options="failinfo" >
			</connection>
		</port>
		<variable id="VariableNuevo" scope="task"  type="sql" config="1"   tokenlink="" documentsource="select summary as resumen,translate( description,chr(13),'.') as descripcion,type as tipo,milestone as hito,owner as propietario from ticket" >
		</variable>
      		<autofilter id="Nuevo_Propietarios" type="split" source="Aceptado" query="select owner from ticket" tokenlink="" report="yes"> 
		</autofilter> 
      		<autofilter id="Nuevo_Componentes" type="split" source="Aceptado" query="select component from ticket" tokenlink="" report="yes"> 
		</autofilter> 
		<autofilter id="Nuevo_Hito" type="split" source="Aceptado" query="select milestone from ticket" tokenlink="" report="yes"> 
		</autofilter> 

		<autofilter id="Generacion" type="split" source="Aceptado" query="select time from ticket" tokenlink="" report="yes"> 
		</autofilter> 
		<autofilter id="Nuevo_Tipo" type="split" source="Aceptado" query="select type from ticket" tokenlink="" report="yes"> 
		</autofilter> 
	</task>
	<task id="FaltaInfo"  title="faltan_datos" >
                <port side="forward" type="split" >
                        <connection source="Aceptado" query="select status from ticket"  options="accepted" >
			</connection>
		</port>
		<variable id="VariableFaltaInfo" scope="task"  type="sql" config="1"   tokenlink="" documentsource="select summary as resumen,description as descripcion,type as tipo,milestone as hito,owner as propietario from ticket" >
		</variable>
      		<autofilter id="FaltaInfo_Propietarios" type="split" source="PorCerrar" query="select owner from ticket" tokenlink="" report="yes"> 
		</autofilter> 
		<autofilter id="FaltaInfo_Hito" type="split" source="PorCerrar" query="select milestone from ticket" tokenlink="" report="yes"> 
		</autofilter> 
		<autofilter id="FaltaInfo_Tipo" type="split" source="PorCerrar" query="select type from ticket" tokenlink="" report="yes"> 
		</autofilter> 

	</task>


	<task id="Aceptado"  title="en_ejecucion" >
                <port side="forward" type="split" >
                        <connection source="EnProgreso" query="select status from ticket"  options="progressin" >
			</connection>
		</port>
		<variable id="VariableAceptado" scope="task"  type="sql" config="1"   tokenlink="" documentsource="select summary as resumen,description as descripcion,type as tipo,milestone as hito,owner as propietario from ticket" >
		</variable>
      		<autofilter id="Aceptado_Propietarios" type="split" source="PorCerrar" query="select owner from ticket" tokenlink="" report="yes"> 
		</autofilter> 
		<autofilter id="Aceptado_Hito" type="split" source="PorCerrar" query="select milestone from ticket" tokenlink="" report="yes"> 
		</autofilter> 
		<autofilter id="Aceptado_Tipo" type="split" source="PorCerrar" query="select type from ticket" tokenlink="" report="yes"> 
		</autofilter> 

	</task>
	<task id="EnProgreso"  title="implementando" >
                <port side="forward" type="split" >
                        <connection source="PorCerrar" query="select status from ticket"  options="closed" >
			</connection>
		</port>
		<variable id="VariableEnProgreso" scope="task"  type="sql" config="1"   tokenlink="" documentsource="select summary as resumen,description as descripcion,type as tipo,milestone as hito,owner as propietario from ticket" >
		</variable>
      		<autofilter id="EnProgreso_Propietarios" type="split" source="PorCerrar" query="select owner from ticket" tokenlink="" report="yes"> 
		</autofilter> 
		<autofilter id="EnProgreso_Hito" type="split" source="PorCerrar" query="select milestone from ticket" tokenlink="" report="yes"> 
		</autofilter> 
		<autofilter id="EnProgreso_Tipo" type="split" source="PorCerrar" query="select type from ticket" tokenlink="" report="yes"> 
		</autofilter> 
	</task>

        <task id="PorCerrar"  title="por_firmar" >
                <port side="forward" type="split" >
                        <connection source="FirmadoVB" query="VariablePorCerrar SIGN Victor Bravo;Antonio Araujo Brett"  options="">
			</connection>
		</port>
		<variable id="VariablePorCerrar" scope="task"  type="sql" config="1"   tokenlink="" documentsource="select id,summary as resumen,description as descripcion,type as tipo,milestone as hito,owner as propietario from ticket" >
		</variable>
      		<autofilter id="PorCerrar_Propietarios" type="split" source="FirmadoVB" query="select owner from ticket" tokenlink="" report="yes"> 
		</autofilter> 
		<autofilter id="PorCerrar_Hito" type="split" source="FirmadoVB" query="select milestone from ticket" tokenlink="" report="yes"> 
		</autofilter> 
	</task>
	<task id="FirmadoVB"  title="Victor Bravo" >
                <port side="forward" type="split" >
                        <connection source="FirmadoAA" query="VariablePorCerrar SIGN Antonio Araujo Brett,Victor Bravo" options="" >
			</connection>
		</port>
		<variable id="VariableFirmadoVB" scope="task"  type="sql" config="1"   tokenlink="" documentsource="select  summary as resumen,description as descripcion,type as tipo,milestone as hito,owner as propietario from ticket" >
		</variable>
      		<autofilter id="FCPropietarios" type="split" source="FirmadoAA" query="select owner from ticket" tokenlink="" report="yes"> 
		</autofilter> 
      		<autofilter id="FCComponentes" type="split" source="FirmadoAA" query="select component from ticket" tokenlink="" report="yes"> 
		</autofilter> 
	</task>
	<task id="FirmadoAA"  title="AntonioAraujo" >
                <port side="forward" type="split" >
                        <connection source="final" query="true" options="" >
			</connection>
		</port>
		<variable id="VariableFirmadoAA" scope="task"  type="sql" config="1"   tokenlink="" documentsource="select  summary as resumen,description as descripcion,type as tipo,milestone as hito,owner as propietario from ticket" >
		</variable>
      		<autofilter id="FCPropietarios" type="split" source="Aceptado" query="select owner from ticket" tokenlink="" report="yes"> 
		</autofilter> 
      		<autofilter id="FCComponentes" type="split" source="Aceptado" query="select component from ticket" tokenlink="" report="yes"> 
		</autofilter> 
	</task>

	<condition id="final">
		<port side="forward" type="split">
			<connection source="">
			</connection>
		</port>
	</condition>
</workflow>
	<configuration id="1" connectstring="psql:seguridad.cenditel.gob.ve:ticket:vbravo:vbravo_">
	</configuration>
</yawl>

=== victorrbravo/gestioninterna/gestioninterna/.safet/flowfiles/SolicitudVistaVacacionesUser.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--
Documento  : tickets.xml
Creado     : 16/10/08 09:27 AM
Autor      : nombre_autor
Descripcion: Archivo generado por plantilla de la Libreria SAFET
-->

<!--<!DOCTYPE yawl SYSTEM "http://trac-safet.cenditel.gob.ve/dtd/yawlworkflow.dtd">-->
<!DOCTYPE yawl SYSTEM "file:///home/vbravo/.safet/dtd/yawlworkflow.dtd">
<yawl  version="0.01">
<workflow id="Generar planilla de solicitud de vista_vacaciones" desc="Planilla que se generar con los datos de una solicitud de vista_vacaciones">
<token key="id"  keysource="vista_vacaciones">
</token>
    
<condition id="inicial" type="start">
	<port side="forward" type="split"  >
		<connection   source="Por_usuario" query="select usuario from vista_vacaciones"  options="_USERNAME" tokenlink="" >
		</connection>
	</port>
</condition>
<task id="Por_usuario"  title="{#ByUserCedula}" >
	<port side="forward" type="split"  >
	<connection   source="Iniciado" query="select status from vista_vacaciones"  options="iniciado" tokenlink="" >
		</connection>
	</port>
	 <variable id="vPor_usuario" scope="task"  type="sql" config="1"   tokenlink="" 
                documentsource="select id,id_cedula, nombres_suplente_1,nombres_suplente_2,cargo_suplente_1,cargo_suplente_2,status,nombreapellido, diasadisfrutar, diasdisfrutados, diassolicitados, diaspordisfrutar, fechasolicitud, fechainicio, fechafin, cedula_suplente_1, cedula_suplente_2, vista_vacaciones.cargo, vista_vacaciones.fecha_ingreso, nombre, vista_vacaciones.departamento, cargo_1, cargo_2, vista_vacaciones.fechaincorporacion, fechafin, diasinhabiles, diasadicionales, bonoacancelar, sueldodelmes, sueldoanticipado, totalapagar, observaciones_talento_humano, observaciones_direccion_ejecutiva,nombre_cuenta_correo_electronico, observaciones_presidencia from vista_vacaciones"
 rolfield=""  timestampfield="" groupby="ORDER BY id DESC" 

 >
     </variable>
</task>


<task id="Iniciado"  title="todas" >
	<port side="forward" type="split"  >
		<connection   source="TalentoHumano" query="select status from vista_vacaciones"  options="Talento_humano" tokenlink="" >
		</connection>
	</port>
	 <variable id="vIniciado" scope="task"  type="sql" config="1"   tokenlink="" 
                documentsource="select id,id_cedula, nombres_suplente_1,nombres_suplente_2,cargo_suplente_1,cargo_suplente_2,status,nombreapellido, diasadisfrutar, diasdisfrutados, diassolicitados, diaspordisfrutar, fechasolicitud, fechainicio, fechafin, cedula_suplente_1, cedula_suplente_2, vista_vacaciones.cargo, vista_vacaciones.fecha_ingreso, nombre, vista_vacaciones.departamento, cargo_1, cargo_2, vista_vacaciones.fechaincorporacion, fechafin, diasinhabiles, diasadicionales, bonoacancelar, sueldodelmes, sueldoanticipado, totalapagar, observaciones_talento_humano, observaciones_direccion_ejecutiva,nombre_cuenta_correo_electronico, observaciones_presidencia from vista_vacaciones" >
     </variable>
</task>
<task id="TalentoHumano"  title="todas" >
	<port side="forward" type="split" pattern="or" >
		<connection   source="DireccionInterna" query="select status from vista_vacaciones"  options="Direccion_interna" tokenlink="" >
		</connection>
		<connection   source="Iniciado" query="select status from vista_vacaciones"  options="iniciado" tokenlink="" back="yes" >
		</connection>

	</port>
	 <variable id="vTalentoHumano" scope="task"  type="sql" config="1"   tokenlink="" 
                documentsource="select id,id_cedula, nombres_suplente_1,nombres_suplente_2,cargo_suplente_1,cargo_suplente_2,status,nombreapellido, diasadisfrutar, diasdisfrutados, diassolicitados, diaspordisfrutar, fechasolicitud, fechainicio, fechafin, cedula_suplente_1, cedula_suplente_2, vista_vacaciones.cargo, vista_vacaciones.fecha_ingreso, nombre, vista_vacaciones.departamento, cargo_1, cargo_2, vista_vacaciones.fechaincorporacion, fechafin, diasinhabiles, diasadicionales, bonoacancelar, sueldodelmes, sueldoanticipado, totalapagar, observaciones_talento_humano, observaciones_direccion_ejecutiva,nombre_cuenta_correo_electronico, observaciones_presidencia from vista_vacaciones"
groupby="ORDER BY id DESC" 
>
     </variable>
</task>

<task id="DireccionInterna"  title="Planilla vista_vacaciones" >
	<port side="forward" type="split"   pattern="none" >
	    <connection source="DireccionEjecutiva" query="select status from vista_vacaciones" options="Direccion_ejecutiva" >	       
        </connection>	
	</port>
	 <variable id="vDireccionInterna" scope="task"  type="sql" config="1"   tokenlink=""
                 documentsource="select id,id_cedula, nombres_suplente_1,nombres_suplente_2,cargo_suplente_1,cargo_suplente_2,status,nombreapellido, diasadisfrutar, diasdisfrutados, diassolicitados, diaspordisfrutar, fechasolicitud, fechainicio, fechafin, cedula_suplente_1, cedula_suplente_2, vista_vacaciones.cargo, vista_vacaciones.fecha_ingreso, nombre, vista_vacaciones.departamento, cargo_1, cargo_2, vista_vacaciones.fechaincorporacion, fechafin, diasinhabiles, diasadicionales, bonoacancelar, sueldodelmes, sueldoanticipado, totalapagar, observaciones_talento_humano, observaciones_direccion_ejecutiva,nombre_cuenta_correo_electronico, observaciones_presidencia from vista_vacaciones"

 >
     </variable>
</task>

<task id="DireccionEjecutiva"  title="Planilla vista_vacaciones" >
	<port side="forward" type="split"   pattern="none" >
	    <connection source="Finanzas" query="select status from vista_vacaciones" options="Finanzas" >
        </connection>	
	
	</port>
	 <variable id="vDireccionEjecutiva" scope="task"  type="sql" config="1"   tokenlink=""
                 documentsource="select id,id_cedula, nombres_suplente_1,nombres_suplente_2,cargo_suplente_1,cargo_suplente_2,status,nombreapellido, diasadisfrutar, diasdisfrutados, diassolicitados, diaspordisfrutar, fechasolicitud, fechainicio, fechafin, cedula_suplente_1, cedula_suplente_2, vista_vacaciones.cargo, vista_vacaciones.fecha_ingreso, nombre, vista_vacaciones.departamento, cargo_1, cargo_2, vista_vacaciones.fechaincorporacion, fechafin, diasinhabiles, diasadicionales, bonoacancelar, sueldodelmes, sueldoanticipado, totalapagar, observaciones_talento_humano, observaciones_direccion_ejecutiva,nombre_cuenta_correo_electronico, observaciones_presidencia from vista_vacaciones"

 >
     </variable>
</task>
<task id="Finanzas"  title="Aprobacion del Presidente" >
	<port side="forward" type="split" pattern="none" >
		<connection source="Archivar_solicitud_procesada" query="select status from vista_vacaciones" options="Archivar_solicitud_procesada" tokenlink="" >
		</connection>
		
	</port>
	 <variable id="vFinanzas" scope="task"  type="sql" config="1"   tokenlink=""
                 documentsource="select id,id_cedula, nombres_suplente_1,nombres_suplente_2,cargo_suplente_1,cargo_suplente_2,status,nombreapellido, diasadisfrutar, diasdisfrutados, diassolicitados, diaspordisfrutar, fechasolicitud, fechainicio, fechafin, cedula_suplente_1, cedula_suplente_2, vista_vacaciones.cargo, vista_vacaciones.fecha_ingreso, nombre, vista_vacaciones.departamento, cargo_1, cargo_2, vista_vacaciones.fechaincorporacion, fechafin, diasinhabiles, diasadicionales, bonoacancelar, sueldodelmes, sueldoanticipado, totalapagar, observaciones_talento_humano, observaciones_direccion_ejecutiva,nombre_cuenta_correo_electronico, observaciones_presidencia from vista_vacaciones"

 >
     </variable>
</task>
<task id="Archivar_solicitud_procesada"  title="solicitud_archivada" >
	<port side="forward" type="split"  pattern="or">
		<connection source="final" query="true" options="" tokenlink="" >
		</connection>
	      <connection   source="TalentoHumano" query="select status from vista_vacaciones"  options="Talento_humano" tokenlink="" back="yes" >
		</connection>
	</port>
	 <variable id="vArchivar" scope="task"  type="sql" config="1"   tokenlink=""
                 documentsource="select id,id_cedula, nombres_suplente_1,nombres_suplente_2,cargo_suplente_1,cargo_suplente_2,status,nombreapellido, diasadisfrutar, diasdisfrutados, diassolicitados, diaspordisfrutar, fechasolicitud, fechainicio, fechafin, cedula_suplente_1, cedula_suplente_2, vista_vacaciones.cargo, vista_vacaciones.fecha_ingreso, nombre, vista_vacaciones.departamento, cargo_1, cargo_2, vista_vacaciones.fechaincorporacion, fechafin, diasinhabiles, diasadicionales, bonoacancelar, sueldodelmes, sueldoanticipado, totalapagar, observaciones_talento_humano, observaciones_direccion_ejecutiva,nombre_cuenta_correo_electronico, observaciones_presidencia from vista_vacaciones"
 rolfield=""  timestampfield="" 
 >
     </variable>
</task>
<condition id="final">
	<port side="forward" type="split">
		<connection source="">
		</connection>
	</port>
</condition>
</workflow>
	<configuration id="1" connectstring="psql:seguridad.cenditel.gob.ve:ticket:vbravo:vbravo_">
	</configuration>
</yawl>

=== victorrbravo/gestioninterna/gestioninterna/.safet/flowfiles/SolicitudVistaVacaciones.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--
Documento  : tickets.xml
Creado     : 16/10/08 09:27 AM
Autor      : nombre_autor
Descripcion: Archivo generado por plantilla de la Libreria SAFET
-->
<!--<!DOCTYPE yawl SYSTEM "http://trac-safet.cenditel.gob.ve/dtd/yawlworkflow.dtd">-->
<!DOCTYPE yawl SYSTEM "file:///home/vbravo/.safet/dtd/yawlworkflow.dtd">
<yawl  version="0.01">
<workflow id="Generar planilla de solicitud de vista_vacaciones" desc="Planilla que se generar con los datos de una solicitud de vista_vacaciones">
<token key="vista_vacaciones.id"  keysource="vista_vacaciones">
</token>
<parameter type="" icon="hito.png" desc= "ByPeriod" mandatory="no" options=""  
	  title="ByPeriod" defaultvalue="0">
</parameter>	
     
<condition id="inicial" type="start">
	<port side="forward" type="split"  >
		<connection   source="Por_usuario" query="select id from vista_vacaciones"  options="{#ByPeriod}" tokenlink="" >
		</connection>
	</port>
</condition>
<task id="Por_usuario"  title="_USERNAME" >
	<port side="forward" type="split"  >
		<connection   source="Vacaciones_solicitadas" query="select status from vista_vacaciones"  options="Archivar_solicitud_procesada" tokenlink="[cedula,id_cedula:vista_vacaciones]" >
		</connection>

	</port>
	 <variable id="vSolicitud" scope="task"  type="sql" config="1"   tokenlink="" 
                documentsource="select id_cedula, nombreapellido, diasadisfrutar, diasdisfrutados, diassolicitados, diaspordisfrutar, fechasolicitud, fechainicio, fechafin, suplenteinterno_1, suplenteinterno_2, cedula_suplente_1, cedula_suplente_2, vista_vacaciones.cargo, vista_vacaciones.fecha_ingreso, nombre, vista_vacaciones.departamento, cargo_1, cargo_2, vista_vacaciones.fechaincorporacion, fechafin, diasinhabiles, diasadicionales, bonoacancelar, sueldodelmes, sueldoanticipado, totalapagar, observaciones_talento_humano, observaciones_direccion_ejecutiva, observaciones_presidencia,nombre_cuenta_correo_electronico from vista_vacaciones"
 rolfield=""  timestampfield="" 

 >
     </variable>
</task>

<task id="Vacaciones_solicitadas"  title="Planilla vista_vacaciones" >
	<port side="forward" type="split"  >
	    <connection source="Solicitud_firmada" query="vSolicitud SIGN #ANYBODY#" options="yes" tokenlink="" 
>
        </connection>
	</port>
	 <variable id="vVacaciones_solicitadas" scope="task"  type="sql" config="1"   tokenlink="" 
                documentsource="select id_cedula, nombreapellido, diasadisfrutar, diasdisfrutados, diassolicitados, diaspordisfrutar, fechasolicitud, fechainicio, fechafin, suplenteinterno_1, suplenteinterno_2, cedula_suplente_1, cedula_suplente_2, vista_vacaciones.cargo, vista_vacaciones.fecha_ingreso, nombre, vista_vacaciones.departamento, cargo_1, cargo_2, vista_vacaciones.fechaincorporacion, fechafin, diasinhabiles, diasadicionales, bonoacancelar, sueldodelmes, sueldoanticipado, totalapagar, observaciones_talento_humano, observaciones_direccion_ejecutiva, observaciones_presidencia ,nombre_cuenta_correo_electronico from vista_vacaciones"
 rolfield="(select nombre_periodo from vista_vacaciones_registro where vista_vacaciones_registro.id_vista_vacaciones=vista_vacaciones.id and vista_vacaciones_registro.status='Archivar_solicitud_procesada' limit 1)"  timestampfield="(select fecha_accion from vista_vacaciones_registro where vista_vacaciones_registro.id_vista_vacaciones=vista_vacaciones.id and vista_vacaciones_registro.status='Archivar_solicitud_procesada' limit 1)" 

 >
     </variable>
</task>
<task id="Solicitud_firmada"  title="Planilla vista_vacaciones" >
	<port side="forward" type="split"  >
		<connection   source="DireccionEjecutiva" query="select status from vista_vacaciones"  options="Direccion_ejecutiva" tokenlink="" >
		</connection>

	</port>
	 <variable id="vFirmadas" scope="task"  type="sql" config="1"   tokenlink="" 
                documentsource="select id_cedula, nombreapellido, diasadisfrutar, diasdisfrutados, diassolicitados, diaspordisfrutar, fechasolicitud, fechainicio, fechafin, suplenteinterno_1, suplenteinterno_2, cedula_suplente_1, cedula_suplente_2, vista_vacaciones.cargo, vista_vacaciones.fecha_ingreso, nombre, vista_vacaciones.departamento, cargo_1, cargo_2, vista_vacaciones.fechaincorporacion, fechafin, diasinhabiles, diasadicionales, bonoacancelar, sueldodelmes, sueldoanticipado, totalapagar, observaciones_talento_humano, observaciones_direccion_ejecutiva, observaciones_presidencia ,nombre_cuenta_correo_electronico from vista_vacaciones"
 rolfield="cn::Victor Rafael Bravo Bravo"  timestampfield="cn::Victor Rafael Bravo Bravo"

 >
     </variable>
</task>
<task id="DireccionEjecutiva"  title="Planilla vista_vacaciones" >
	<port side="forward" type="split"  >
	    <connection source="final" query="true" options="" >
        </connection>
	</port>
	 <variable id="vDireccionEjecutiva" scope="task"  type="sql" config="1"   tokenlink="" 
                documentsource="select  personal.cargo, personal.departamento, diasadisfrutar, diasdisfrutados, diaspordisfrutar, diassolicitados, suplenteinterno_1, suplenteinterno_2, fechasolicitud, nombre, vista_vacaciones.fecha_ingreso, informacion_usuario, nombre, fechainicio, fechafin from vista_vacaciones"
 rolfield=""  timestampfield="" 

 >
     </variable>
</task>

<condition id="final">
	<port side="forward" type="split">
		<connection source="">
		</connection>
	</port>
</condition>

</workflow>
	<configuration id="1" connectstring="psql:seguridad.cenditel.gob.ve:ticket:vbravo:vbravo_">
	</configuration>
</yawl>
