=== victorrbravo/gestioninterna/gestioninterna/.safet/dtd/yawlinput.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : yawlinput.dtd
    Created on : 21 de junio de 2010, 15:46
    Author     : pbuitrago
    Description:
        Lenguaje para entrada de datos de SAFET
-->

<!-- TODO define your own vocabulary/syntax. Example follows:  -->
<!ELEMENT operations (operation*) > <!-- operations va a tener como elemento: operation -->

<!ATTLIST operations	suffix CDATA #IMPLIED 
			commandname CDATA #IMPLIED >

<!ELEMENT operation (parameter|command)*  > <!-- operation va a tener como elemento: command -->
<!ATTLIST operation   	name CDATA #IMPLIED  
			desc CDATA #IMPLIED
			action CDATA #IMPLIED
			dataaction CDATA #IMPLIED
			postaction CDATA #IMPLIED
			subtitle  (yes|no) "no"
			icon CDATA #IMPLIED >

<!ELEMENT command (fields) > <!-- command va a tener como elemento: fields -->
<!ATTLIST command       id CDATA #IMPLIED  
                        type (actualizar|eliminar|agregar) "agregar"
                        table CDATA #IMPLIED > 
<!ELEMENT parameter (#PCDATA)  >
<!ATTLIST parameter	type CDATA #IMPLIED   
			mandatory CDATA #IMPLIED
			title CDATA #IMPLIED
			primarykey (yes|no) "no"
			validation CDATA #IMPLIED 
			options CDATA #IMPLIED
			function CDATA #IMPLIED 
			format (time_t|integer) "time_t" 
			desc CDATA #IMPLIED
			literal CDATA #IMPLIED
			sequence CDATA #IMPLIED
			typesequence (next|current) "next"
			input CDATA #IMPLIED
			path CDATA #IMPLIED
			visible CDATA #IMPLIED
 			order (asc|desc|none) "asc" 
			icon CDATA #IMPLIED
			index CDATA #IMPLIED  
			filter CDATA #IMPLIED 
			repetible (yes|no) "no"
			configurekey CDATA #IMPLIED 
			defaultvalue CDATA #IMPLIED > 

<!ELEMENT fields (field+) > <!-- fields va a tener como elemento: field -->
			  

<!ELEMENT field (#PCDATA) > <!-- no tiene elemento -->
<!ATTLIST field		type CDATA #IMPLIED   
			mandatory CDATA #IMPLIED
			title CDATA #IMPLIED
			primarykey (yes|no) "no"
			validation CDATA #IMPLIED 
			options CDATA #IMPLIED
			function CDATA #IMPLIED 
			format (time_t|integer) "time_t" 
			desc CDATA #IMPLIED
			literal CDATA #IMPLIED
			sequence CDATA #IMPLIED
			typesequence (next|current) "next"
			input CDATA #IMPLIED
			path CDATA #IMPLIED
			visible CDATA #IMPLIED
 			order (asc|desc|none) "asc" 
			icon CDATA #IMPLIED
			position CDATA #IMPLIED
			index CDATA #IMPLIED  
			filter CDATA #IMPLIED
			changefor CDATA #IMPLIED
			changekey CDATA #IMPLIED 
			enablethis CDATA #IMPLIED
	    	        repetible (yes|no) "no" >

=== victorrbravo/gestioninterna/gestioninterna/.safet/input/defconsole.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--
Documento  : deftrac.xml
Creado     : Víctor Bravo
Autor      : Victor Bravo
Descripcion: Archivo de Entrada para SAFET - Inflow
-->
<!DOCTYPE operations SYSTEM "file:///home/vbravo/.safet/dtd/yawlinput.dtd">
<operations suffix=":" commandname="operacion"  >  
<operation  name="Reportes"  desc="Reportes, Listas, Formas" icon="report.png">
</operation>


<operation  name="Listar_datos_general" >
<command id ="1" type="agregar" table="lista">
        <fields>
                <field type="filename" mandatory="yes" title="Cargar_archivo_flujo" desc="Cargar un archivo de flujo para generar un reporte" filter="Archivos de flujo (*.xml);;Todos (*)" primarykey="yes" changekey="yes" options="">
                        Cargar_archivo_flujo
                </field>
                <field type="combovar" mandatory="yes" validation="\w+" changefor="Cargar_archivo_flujo">
                        Variable
                </field>

        </fields>
</command>
</operation>

<operation  name="Listar_datos" >
<command id ="1" type="agregar" table="lista">
        <fields>
                <field type="filename" mandatory="yes" title="Cargar_archivo_flujo" desc="Cargar un archivo de flujo para generar un reporte" filter="Archivos de flujo (*.xml);;Todos (*)" primarykey="yes" changekey="yes" options="">
                        Cargar_archivo_flujo
                </field>
                <field type="combovar" mandatory="yes" validation="\w+" changefor="Cargar_archivo_flujo">
                        Variable
                </field>

        </fields>
</command>
</operation>
<operation  name="Generar_gráfico_para_clave" >
        <command id ="1" type="agregar" table="vacaciones">
                <fields>
                        <field type="string" literal="/home/vbravo/.safet/flowfiles/SolicitudVistaVacacionesGraph.xml" mandatory="yes" changekey="yes" title="Cargar_archivo_flujo">
                                Cargar_archivo_flujo
                        </field>
                        <field type="combolisttable"
 options="id:vacaciones::'(' || id || ') ' || informacion_usuario" mandatory="yes" primarykey="no" title="Clave">
                                Clave
                        </field>

                </fields>
        </command>
</operation>



<operation  name="Generar_gráfico_para_clave_proyecto_AUTANA" >
        <command id ="1" type="agregar" table="ticket">
                <fields>
                        <field type="string" literal="/home/vbravo/.safet/flowfiles/flujoAppPlanificacionAUTANA.xml" mandatory="yes" changekey="yes" title="Cargar_archivo_flujo">
                                Cargar_archivo_flujo
                        </field>
                        <field type="combolisttable"
 options="id:actividad_por_accion:where id=94::'(' || id || ') ' || nombre " mandatory="yes" primarykey="no" title="Clave">
                                Clave
                        </field>

                </fields>
        </command>
</operation>


<operation  name="Generar_gráfico_para_clave_proyecto_Tibisay_seguridad" >
        <command id ="1" type="agregar" table="ticket">
                <fields>
                        <field type="string" literal="/home/vbravo/.safet/flowfiles/actualizacion_software.xml" mandatory="yes" changekey="yes" title="Cargar_archivo_flujo">
                                Cargar_archivo_flujo
                        </field>

                        <field type="combolisttable"
 options="id:actividad_por_accion:where id=88::'(' || id || ') ' || nombre " mandatory="yes" primarykey="no" title="Clave">
                                Clave
                        </field>

                </fields>
        </command>
</operation>

<operation  name="Listar_datos_para_clave_Solicitud_vacaciones" >
        <command id ="1" type="agregar" table="vacaciones">
                <fields>
                        <field type="string" literal="/home/vbravo/.safet/flowfiles/SolicitudVistaVacacionessp.xml" mandatory="yes" changekey="yes" title="Cargar_archivo_flujo" >
                                Cargar_archivo_flujo
                        </field>

                        <field type="combolisttable"
 options="id:vacaciones::'(' || id || ') ' || informacion_usuario " mandatory="yes" primarykey="no" title="Clave">
                                Clave
                        </field>
                </fields>
        </command>
</operation>

<operation  name="Seguimiento General"  desc="Gráficos de proyectos" icon="graph.png">
</operation>
<operation  name="Generar_gráfico_coloreado" >
	<command id ="1" type="agregar" table="lista" >
		<fields>
			<field type="filename" mandatory="yes" title="Cargar_archivo_flujo" desc="Cargar un archivo de flujo para generar un reporte" filter="Archivos de flujo (*.xml);;Todos (*)" primarykey="yes" changekey="yes" options="show::id,selected::1;2;3;4;5;6;7;8;9;10">
				Cargar_archivo_flujo
			</field>
		</fields>
	</command>
</operation>

<operation  name="Seguimiento por reunión de Consejo Directivo"  desc="Acciones para cambiar de estado un proyecto" icon="planning.png">
</operation>

<operation  name="Generar_gráfico_para_clave_reuniones" >
	<command id ="1" type="agregar" table="reuniones">
		<fields>
	                <field type="string" literal="/home/vbravo/.safet/flowfiles/FlujoGestionReunionesConsejoDirectivo.xml" mandatory="yes" changekey="yes" title="Cargar_archivo_flujo">
	                        Cargar_archivo_flujo
	                </field>

			<field type="combolisttable"
 options="id:reuniones::'(' || id || ') ' || descripcion " mandatory="yes" primarykey="no" title="Clave">
				Clave
			</field>
		</fields>
	</command>
</operation>

<operation  name="Generar_gráfico_para_clave_Solicitud_de_vacaciones" >
        <command id ="1" type="agregar" table="vacaciones">
                <fields>
                        <field type="string" literal="/home/vbravo/.safet/flowfiles/SolicitudVistaVacacionessp.xml" mandatory="yes" changekey="yes" title="Cargar_archivo_flujo">
                                Cargar_archivo_flujo
                        </field>

                        <field type="combolisttable"
 options="id:vacaciones:where usuario='_USERNAME'::'(' || id || ') ' || informacion_usuario" mandatory="yes" primarykey="no" title="Clave">
                                Clave
                        </field>
                </fields>
        </command>
</operation>
<operation  name="Generar_gráfico_para_clave_vacaciones" >
        <command id ="1" type="agregar" table="vacaciones">
                <fields>
                        <field type="string" literal="/home/vbravo/.safet/flowfiles/SolicitudVistaVacacionessp.xml" mandatory="yes" changekey="yes" title="Cargar_archivo_flujo">
                                Cargar_archivo_flujo
                        </field>

                        <field type="combolisttable"
 options="id:vacaciones:where fechasolicitud > 1380601740::'(' || id || ') ' || informacion_usuario" mandatory="yes" primarykey="no" title="Clave" order="desc" >
                                Clave
                        </field>
                </fields>
        </command>
</operation>



<operation  name="Seguimiento de las correspondencias y denuncias"  desc="Acciones para cambiar de estado una correspondencia y denuncias" icon="planning.png">
</operation>

<operation  name="Generar_gráfico_para_clave_correspondencia_y_denuncias" >
        <command id ="1" type="agregar" table="correspondencia">
                <fields>
                        <field type="string" literal="/home/vbravo/.safet/flowfiles/FlujoControldeCorrespondencia.xml" mandatory="yes" changekey="yes" title="Cargar_archivo_flujo">
                                Cargar_archivo_flujo
                        </field>

                        <field type="combolisttable"
 options="id:correspondencia::'(' || id || ') ' || 'Procedencia: ' || procedencia || ' Asunto: ' || asunto " mandatory="yes" primarykey="no" title="Clave">
                                Clave
                        </field>
                </fields>
        </command>
</operation>

<operation  name="Generar_gráfico_para_clave_Solicitud_correspondencia_guarura" >
        <command id ="1" type="agregar" table="correspondencia">
                <fields>
                        <field type="string" literal="/home/vbravo/.safet/flowfiles/FlujoControldeCorrespondenciaGuarura.xml" mandatory="yes" changekey="yes" title="Cargar_archivo_flujo" >
                                Cargar_archivo_flujo
                        </field>

                        <field type="combolisttable"
 options="id_guarura:correspondencia::'(' || id_guarura || ') ' || 'Procedencia: ' || procedencia || ' Asunto: ' || asunto" mandatory="yes" primarykey="no" title="Clave">
                                Clave
                        </field>
                </fields>
        </command>
</operation>


</operations>

=== victorrbravo/gestioninterna/gestioninterna/.safet/input/defusers.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--
Documento  : deftrac.xml
Creado     : Víctor Bravo
Autor      : Victor Bravo
Descripcion: Archivo de Entrada para SAFET - Inflow
-->
<!DOCTYPE operations SYSTEM "file:///home/debian/.safet/dtd/yawlinput.dtd">
<operations suffix=":" commandname="operacion" >  
<operation  name="Usuarios"  desc="Agregar,Modificar,Eliminar,Listar" icon="user.png">
</operation>
<operation  name="Agregar_usuario" >
<command id ="1" type="agregar" table="lista">
	<fields>
		<field type="string" mandatory="yes" primarykey="yes" options=""  title="Nombre_cuenta_usuario">
			auth.account.*
		</field>
		<field type="string" mandatory="no" options="echoMode::Password"  title="Contraseña_usuario">
			auth.pass.*
		</field>
		<field type="string" mandatory="no" title="Nombre_completo_usuario">
			auth.realname.*
		</field>
		<field type="comboconffile" mandatory="no" options="Roles/name.*"  	title="Rol_del_Usuario">
			auth.role.*
		</field>

	</fields>
</command>
</operation>
<operation  name="Generar_ticket" >
<command id ="1" type="actualizar" table="lista">
	<fields>
		<field type="string" mandatory="yes" options=""  title="Periodo_vacacional">
			Periodo_vacacional
		</field>
	    <field type="string" mandatory="yes" title="Asunto">
			Asunto
		</field>
	    <field type="string" mandatory="yes" title="Destinatarios">
			Destinatarios
		</field>
	    <field type="string" mandatory="yes" title="accion">
			accion
		</field>
	    <field type="string" mandatory="no" title="Emailtemplate">
			Emailtemplate
		</field>
	    <field type="string" mandatory="yes" title="Nombre_operacion">
			Nombre_operacion
		</field>
	</fields>
</command>
</operation>

<operation  name="Modificar_usuario" >
<command id ="1" type="actualizar" table="lista">
	<fields>
		<field type="comboconffile" mandatory="yes" options="Auth/account.*"  title="Nombre_cuenta_usuario">
			auth.account.*
		</field>
		<field type="string" mandatory="no" options="echoMode::Password"  title="Contrasena_usuario">
			auth.pass.*
		</field>
		<field type="string" mandatory="no" title="Nombre_completo_usuario">
			auth.realname.*
		</field>

		<field type="string" mandatory="no" title="Rol_usuario">
			auth.role.*
		</field>
		<field type="string" mandatory="no" title="Tickets_usuario">
			auth.tickets.*
		</field>

	</fields>
</command>
</operation>
<operation  name="Borrar_usuario" >
<command id ="1" type="eliminar" table="Auth">
	<fields>
		<field type="comboconffile" mandatory="yes" options="Auth/account.*"  title="Nombre_cuenta_usuario">
			auth.account.*
		</field>

	</fields>
</command>
</operation>

<operation  name="Operaciones"  desc="Agregar,Modificar,Eliminar,Listar" icon="firmadoc.png">
</operation>
<operation  name="Modificar_operación" >
<command id ="1" type="actualizar" table="lista">
	<fields>
		<field type="comboconffile" mandatory="yes" options="Permises/operation.*" primarykey="yes"  title="Nombre_operacion">
			permises.operation.*
		</field>
		<field type="listconffile" mandatory="no" options="Auth/account.*" title="Permitido_a_usuarios">
			permises.accounts.*
		</field>
		<field type="string" mandatory="no" title="Tipos_de_permiso">
			permises.types.*
		</field>
		<field type="listconffile" mandatory="no" options="Roles/name.*"  title="Permitido_a_roles">
			permises.roles.*
		</field>

	</fields>
</command>
</operation>
<operation  name="Roles"  desc="Agregar,Modificar,Eliminar,Listar" icon="user.png">
</operation>
<operation  name="Agregar_rol" >
<command id ="1" type="agregar" table="Roles">
	<fields>
		<field type="string" mandatory="yes" primarykey="yes" options=""  title="Nombre_Rol">
			roles.name.*
		</field>
		<field type="stringbox" mandatory="no" options=""  title="Descripción">
			roles.description.*
		</field>

	</fields>
</command>
</operation>
<operation  name="Modificar_rol" >
<command id ="1" type="actualizar" table="lista">
	<fields>
		<field type="comboconffile" primarykey="yes" mandatory="yes" options="Roles/name.*" title="Nombre_rol">
			roles.name.*
		</field>
		<field type="string" mandatory="no"   title="Descripción">
			roles.description.*
		</field>
	</fields>
</command>
</operation>
<operation  name="Borrar_rol" >
<command id ="1" type="eliminar" table="Roles">
	<fields>
		<field type="comboconffile" mandatory="yes" options="Roles/name.*"  title="Nombre_cuenta_usuario">
			roles.name.*
		</field>

	</fields>
</command>
</operation>
</operations>

=== victorrbravo/gestioninterna/gestioninterna/.safet/input/defmanagementsignfile.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--
Documento  : deftrac.xml
Creado     : Víctor Bravo
Autor      : Victor Bravo
Descripcion: Archivo de Entrada para SAFET - Inflow
-->
<!DOCTYPE operations SYSTEM "file:///home/debian/.safet/dtd/yawlinput.dtd">
<operations suffix=":" commandname="operacion">

<operation  name="Operaciones de Firma" icon="default.png" >
</operation>
<operation  name="Firmar_electronicamente_con_Tarjeta" icon="firmadoc.png" >
<command id ="1" type="agregar" table="ticket">
	<fields>
		<field type="filename" mandatory="no" desc="Cargar Archivo en el contenedor actual para ser firmado" repetible="no" filter="Archivos Adobe PDF (*.pdf);;Archivos de texto (*.txt);;Archivos OpenOffice Writer (*.odt);;Todos (*)" title="Cargar_Archivo_a_Firmar">
			Cargar_Archivo_1
		</field>
		<field type="filename" mandatory="no" desc="Cargar Archivo en el contenedor actual para ser firmado" repetible="no" filter="Archivos Adobe PDF (*.pdf);;Archivos de texto (*.txt);;Archivos OpenOffice Writer (*.odt);;Todos (*)" title="Cargar_Segundo_Archivo_a_Firmar">
			Cargar_Archivo_2
		</field>
		<field type="filename" mandatory="no" desc="Cargar Archivo en el contenedor actual para ser firmado" repetible="no" filter="Archivos Adobe PDF (*.pdf);;Archivos de texto (*.txt);;Archivos OpenOffice Writer (*.odt);;Todos (*)" title="Cargar_Tercer_Archivo_a_Firmar">
			Cargar_Archivo_3
		</field>
		<field type="filename" mandatory="no" desc="Cargar Archivo en el contenedor actual para ser firmado" repetible="no" filter="Archivos Adobe PDF (*.pdf);;Archivos de texto (*.txt);;Archivos OpenOffice Writer (*.odt);;Todos (*)" title="Cargar_Cuarto_Archivo_a_Firmar">
			Cargar_Archivo_4
		</field>

		<field type="filename" options="save," mandatory="contenedores" desc="Nombre y ruta (path) del contenedor (Archivo .ddoc)" repetible="no" validation=".+\.ddoc$" filter="Archivos firmados electrónicamente (*.ddoc);;Todos (*)">
			Nombre_contenedor
		</field>
		<field type="filename" options="" mandatory="contenedores" desc="Nombre y ruta (path) de un contenedor (Archivo .ddoc) existente" repetible="no" validation=".+\.ddoc$" >
		Cargar_contenedor
		</field>
	</fields>
</command>
</operation>
<operation  name="Firmar_electrónicamente_con_P12" icon="firmadoc.png" >
<command id ="1" type="agregar" table="ticket">
	<fields>
		<field type="filename" mandatory="no" desc="Cargar Archivo en el contenedor actual para ser firmado" repetible="yes" filter="Archivos Adobe PDF (*.pdf);;Archivos de texto (*.txt);;Archivos OpenOffice Writer (*.odt);;Todos (*)">
			Cargar_Archivo
		</field>
		<field type="filename" options="save" mandatory="contenedores" desc="Nombre y ruta (path) del contenedor (Archivo .ddoc)" repetible="no" filter="Archivos firmados (*.ddoc);;Todos (*)" validation=".+\.ddoc$">
			Nombre_contenedor
		</field>
		<field type="filename" mandatory="contenedores" desc="Nombre y ruta (path) de un contenedor (Archivo .ddoc) existente" repetible="no" filter="Archivos firmados (*.ddoc);;Todos (*)" validation=".+\.ddoc$">
		Cargar_contenedor
		</field>

	</fields>
</command>
</operation>

<operation  name="Verificar_firma_electrónica"  icon="seal.png"  >
	<command id ="1" type="agregar" table="ticket">
		<fields>
			<field type="filename" mandatory="yes" desc="Cargar Archivo en el contenedor actual para ser firmado" repetible="yes" filter="Archivos digidoc Firmados (*.ddoc);;Todos (*)">
				Cargar_Archivo
		</field>
			
		</fields>
	</command>
</operation>
</operations>
