=== victorrbravo/gestioninterna/gestioninterna/.safet/dtd/yawlworkflow.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : yawlworkflow.dtd
    Created on : 22 de enero de 2008, 15:46
    Author     : vbravo
    Description:
        Una definicion para gestionar archivos de flujos de trabajo (workflow)
        con el lenguaje YAWL (Yet Another Workflow Language) 
        http://www.yawl-system.com dentro del proyecto SAFET :
        Sistema Automatizado para Firma Electronica y Estampillado de Tiempo

    TODO define vocabulary identification data
    PUBLIC ID  : -//vendor//vocabulary//EN
    SYSTEM ID  : http://server/path/yawlworkflow.dtd
-->

<!-- TODO define your own vocabulary/syntax. Example follows:  -->
<!ELEMENT yawl (workflow,configuration*)>
<!ATTLIST yawl
version  CDATA #REQUIRED> <!-- must be "0.01"> -->
<!ELEMENT workflow (token,(task|compositetask|variable|condition|parameter)*)>
<!ELEMENT token (#PCDATA) >
<!ATTLIST token     key CDATA #REQUIRED                    
                    description CDATA #IMPLIED
                    type (sql|file|webpage) "sql"
                    config CDATA #IMPLIED
                    keysource CDATA #REQUIRED>
<!ELEMENT configuration (#PCDATA) >
<!ATTLIST configuration  id CDATA #REQUIRED
                         connectstring CDATA #REQUIRED>
<!ATTLIST workflow  id CDATA #REQUIRED
                    desc CDATA #IMPLIED>
<!ELEMENT task (variable|port|autofilter|recursivefilter)*>
<!ATTLIST task id CDATA #REQUIRED 
               title  CDATA #IMPLIED
               hideuntil  CDATA #IMPLIED
               numericinfo  CDATA #IMPLIED
               textualinfo  CDATA #IMPLIED
	       left CDATA #IMPLIED
	       top CDATA #IMPLIED
	       role CDATA #IMPLIED
	       note CDATA #IMPLIED
               multiplicity (unique|multiple) "unique"
          type (atomic|composite) "atomic"
          report (yes|no) "no"  >
<!ELEMENT compositetask (workflow)>
<!ELEMENT variable (document*)>
<!ATTLIST variable  id CDATA #REQUIRED 
                    tokenlink CDATA #IMPLIED
                    description CDATA #IMPLIED
                    scope (net|task) "net"
                    type (sql|file|webpage) "sql"
                    usage (input|output|inout) "input"
                    config CDATA #IMPLIED
                    source CDATA #IMPLIED
                    rolfield CDATA #IMPLIED
                    timestampfield CDATA #IMPLIED
		    left CDATA #IMPLIED
		    top CDATA #IMPLIED
		    groupby CDATA #IMPLIED
                    documentsource CDATA #REQUIRED>
<!ELEMENT document (#PCDATA)  >
<!ATTLIST document  key CDATA #REQUIRED>
<!ELEMENT connection (#PCDATA) >
<!ATTLIST connection source  CDATA #IMPLIED
		     query CDATA #IMPLIED
		     options CDATA #IMPLIED
		     left CDATA #IMPLIED
		     top CDATA #IMPLIED
		     back CDATA #IMPLIED
		     tokenlink CDATA #IMPLIED>					 
<!ELEMENT port (connection*) >
<!ELEMENT autofilter (#PCDATA) >
<!ATTLIST autofilter id CDATA #REQUIRED 
		side (bottom|down|up|forward) "forward"
	       source  CDATA #REQUIRED
               type (join|split)  #REQUIRED
               query  CDATA #REQUIRED
               subquery  CDATA #IMPLIED
               options  CDATA #IMPLIED		
               tokenlink  CDATA #IMPLIED
               pattern (none|and|or|xor) "or"	       
               report (yes|no) "no"
               subreport (yes|no) "no"
		>
<!ELEMENT recursivefilter (#PCDATA) >
<!ATTLIST recursivefilter id CDATA #REQUIRED 
		side (bottom|down|up|forward) "forward"
	       source  CDATA #REQUIRED
               type (join|split)  #REQUIRED
               query  CDATA #REQUIRED
               options  CDATA #IMPLIED		
               tokenlink  CDATA #IMPLIED
               pattern (none|and|or|xor) "or"
	       initial CDATA #REQUIRED
	       filter CDATA #REQUIRED
               report (yes|no) "no"  
	       onlyfathers (yes|no) "no" >

<!ATTLIST port side (bottom|down|up|forward) #REQUIRED
               type (join|split)  #REQUIRED
               query  CDATA #IMPLIED
               tokenlink  CDATA #IMPLIED
               options  CDATA #IMPLIED
               drop    CDATA #IMPLIED  
	       config CDATA #IMPLIED
               pattern (none|and|or|xor) "none">
<!ELEMENT condition (port+) >
<!ATTLIST condition id CDATA #REQUIRED
               numericinfo  CDATA #IMPLIED
               textualinfo  CDATA #IMPLIED 
	       left CDATA #IMPLIED
	       top CDATA #IMPLIED
               type (start|end|inprocess) "inprocess"
            report (yes|no) "no"  >
<!ELEMENT taskid (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT link (#PCDATA)>
<!ELEMENT source (#PCDATA)>
<!ELEMENT connectstring (#PCDATA)>
<!ELEMENT parameter (#PCDATA)  >
<!ATTLIST parameter	type CDATA #IMPLIED   
			mandatory CDATA #IMPLIED
			title CDATA #IMPLIED
			primarykey (yes|no) "no"
			validation CDATA #IMPLIED 
			options CDATA #IMPLIED
			function CDATA #IMPLIED 
			format (time_t|integer) "time_t" 
			desc CDATA #IMPLIED
			literal CDATA #IMPLIED
			sequence CDATA #IMPLIED
			typesequence (next|current) "next"
			input CDATA #IMPLIED
			path CDATA #IMPLIED
			visible CDATA #IMPLIED
 			order (asc|desc|none) "asc" 
			icon CDATA #IMPLIED
			index CDATA #IMPLIED  
			filter CDATA #IMPLIED 
			repetible (yes|no) "no"
			configurekey CDATA #IMPLIED 
			defaultvalue CDATA #IMPLIED >

=== victorrbravo/gestioninterna/gestioninterna/.safet/flowfiles/vacaciones.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--
Documento  : tickets.xml
Creado     : 16/10/08 09:27 AM
Autor      : nombre_autor
Descripcion: Archivo generado por plantilla de la Libreria SAFET
-->        
<!--<!DOCTYPE yawl SYSTEM "http://trac-safet.cenditel.gob.ve/dtd/yawlworkflow.dtd">-->
<!DOCTYPE yawl SYSTEM "file:///home/vbravo/.safet/dtd/yawlworkflow.dtd">
<yawl  version="0.01">
<workflow id="vacaciones">
        <token key="id"  keysource="vacaciones">
        </token>
<parameter title="Tarea a borrar" path="/home/vbravo/.safet/flowfiles/vacaciones.xml" options="" type="combotask" mandatory="no"/>
 <parameter title="Nodo anterior" path="/home/vbravo/.safet/flowfiles/vacaciones.xml" options="" type="combotask" mandatory="no"/>
<parameter title="Nodo a agregar" path="/home/vbravo/.safet/flowfiles/vacaciones.xml" options="" type="string" mandatory="no"/>
<parameter title="Textualinfo"  options="" type="string" mandatory="no"/>
<parameter title="Paralelo al nodo siguiente"  options="No::No::No,Si::Si::Si" type="combolistliteral" mandatory="no"/>
        <condition id="inicial" type="start">
                <port side="forward" type="split"   >
                         <connection source="Todas" query="select id from vacaciones"  options=">0" >
                        </connection>
                </port>
        </condition>
        <task id="Todas"  title="Todas">
                <port side="forward" type="split" >
                        <connection source="final" query="true" options="" >
                        </connection>
                </port>
                <variable id="vTodas" scope="task"  type="sql" config="1"   tokenlink="" documentsource="select id,id_cedula,diasadisfrutar,diasdisfrutados,diaspordisfrutar,fechainicioperiodo,fechafinperiodo,fechainicio,fechafin,diashabiles,diasinhabiles,bonoacancelar,bonoporcancelar,sueldodelmes,sueldoanticipado,status,suplenteinterno_1,suplenteinterno_2,observaciones_talento_humano,fechaincorporacion,fechasolicitud,totalapagar,informacion_usuario,nombre,fecha_ingreso,usuario,observaciones_direccion_ejecutiva,observaciones_presidencia,diasadicionales,diassolicitados,cedula_suplente_1,cedula_suplente_2,acepta_suplente1,acepta_suplente2 from vacaciones" >
                </variable>
        </task>
<condition id="final">
                <port side="forward" type="split">
                        <connection source="">
                        </connection>
                </port>
        </condition>
</workflow>
        <configuration id="1" connectstring="psql:seguridad.cenditel.gob.ve:ticket:vbravo:vbravo_">
        </configuration>
</yawl>

=== victorrbravo/gestioninterna/gestioninterna/.safet/flowfiles/RecaudacionOperadoraGeneral.xml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE yawl SYSTEM 'file:///home/c30/.safet/dtd/yawlworkflow.dtd'>
<!--
Documento  : RecaudacionOperadora.xml
Creado     : 27/10/2015 09:27 AM
Autor      : Ing. Josè Sulbaràn
Descripcion: Archivo generado por plantilla de la Libreria SAFET
-->

<yawl version="0.01">
 <workflow id="operadora_operadora">
<token keysource="operadora_operadora" key="usuario_operadora_id"/>



<parameter title="Anho" options="" type="string" mandatory="no"/>
 <parameter title="Periodo" options="" type="string" mandatory="no"/>


<!-- ##############################################################################-->

  <condition type="start" id="inicial">
   <port side="forward" type="split">
   <connection query=" select usuario_operadora_id from operadora_operadora" options=">0" source="Operadoras"
      tokenlink=""/>

   </port>
  </condition>
   

<!-- ##############################################################################-->  


  <task title="Generales" id="Operadoras">
   <port side="forward" type="split">
    
    <connection
       query="select  operadora_recaudacion.anho from operadora_operadora" options="{#Anho}"  source="Anho"
       tokenlink="[usuario_operadora_id,operadora_id:operadora_declaracion][recaudacion_id,id:operadora_recaudacion]"/>
       

   </port>
   <variable config="1" documentsource="select razon_social from operadora_operadora" type="sql" 
    tokenlink="" 
    id="vOperadoras" rolfield="" scope="task"
    timestampfield=""/>

  </task>


 <!-- ##############################################################################-->

  <task title="::safethide::" id="Anho"> 
   <port side="forward" type="split" >
    
     <connection query=" select operadora_recaudacion.num_periodo from operadora_operadora" options="{#Periodo}" source="Declarada"
      tokenlink="[usuario_operadora_id,operadora_id:operadora_declaracion][recaudacion_id,id:operadora_recaudacion]"/>
     
   </port>

  <variable config="1" documentsource="select razon_social, operadora_recaudacion.id from operadora_operadora" type="sql" 
    tokenlink="[usuario_operadora_id,operadora_id:operadora_declaracion][recaudacion_id,id:operadora_recaudacion]" 
    id="vAnho" rolfield="" scope="task"
    timestampfield=""/>
 
  </task>

<!-- 
[id,declaracion_id:operadora_detallepago][pago_id,id:operadora_pago] -->
<!-- ##############################################################################-->
  

   <task title="Operadoras que han declarado" id="Declarada"> 
   <port side="forward" type="split" pattern="or" >
    

     <connection query="select operadora_pago.estatus_pago_id from operadora_operadora" options="1"
       source="Pago_Revision" tokenlink="[usuario_operadora_id,operadora_id:operadora_declaracion][recaudacion_id,id:operadora_recaudacion][id,declaracion_id:operadora_detallepago][pago_id,id:operadora_pago]"/>
 
  <connection query=" select operadora_declaracion.moroso from operadora_operadora" options="true" source="Moroso"
      tokenlink="[usuario_operadora_id,operadora_id:operadora_declaracion]"/>
  
        
 
   </port>

  <variable config="1" documentsource="select  operadora_declaracion.id, razon_social, operadora_declaracion.operadora_id, operadora_declaracion.recaudacion_id,  operadora_recaudacion.anho, operadora_recaudacion.num_periodo from operadora_operadora " type="sql" 
    tokenlink="[usuario_operadora_id,operadora_id:operadora_declaracion]" 
    id="vDeclarada" rolfield="" scope="task"
    timestampfield=""/>
 
  </task>

 


<!-- ##############################################################################-->  

<task title="Mora de las operadoras" id="Moroso">
   <port side="forward" type="split">

<connection query=" select operadora_declaracion.convenio_id from operadora_operadora" options=">0" source="Convenio"
      tokenlink="[usuario_operadora_id,operadora_id:operadora_declaracion]"/>
 
         
   </port>
   <variable config="1" documentsource="select razon_social, operadora_declaracion.operadora_id, operadora_declaracion.moroso from operadora_operadora" type="sql" 
    tokenlink="[usuario_operadora_id,operadora_id:operadora_declaracion]" 
    id="vMoroso" rolfield="" scope="task"
    timestampfield=""/>

  </task>

  <!-- ##############################################################################-->  

<task title="Convenios de las operadoras" id="Convenio">
   <port side="forward" type="split">
          
     <connection query="select operadora_pago.estatus_pago_id from operadora_operadora" options="1"
       source="Pago_Revision" tokenlink="[usuario_operadora_id,operadora_id:operadora_declaracion][recaudacion_id,id:operadora_recaudacion][id,declaracion_id:operadora_detallepago][pago_id,id:operadora_pago]"/>
 
         
   </port>
   <variable config="1" documentsource="select  operadora_declaracion.convenio_id, razon_social, operadora_declaracion.operadora_id, operadora_declaracion.id from operadora_operadora" type="sql" 
    tokenlink="[usuario_operadora_id,operadora_id:operadora_declaracion]" 
    id="vConvenio" rolfield="" scope="task"
    timestampfield=""/>

  </task>



<!-- ##############################################################################-->  

  <task title="Pagos de las operadoras en revision" id="Pago_Revision">
   <port side="forward" type="split">
    
     <connection query="select operadora_pago.estatus_pago_id from operadora_operadora" options="2"
       source="Pago_Revisado" tokenlink="[usuario_operadora_id,operadora_id:operadora_declaracion][recaudacion_id,id:operadora_recaudacion][id,declaracion_id:operadora_detallepago][pago_id,id:operadora_pago]"/>



   </port>
   <variable config="1" documentsource="select razon_social from operadora_operadora" type="sql" 
    tokenlink="[usuario_operadora_id,operadora_id:operadora_declaracion][recaudacion_id,id:operadora_recaudacion][id,declaracion_id:operadora_detallepago][pago_id,id:operadora_pago]" 
    id="vPago_Revision" rolfield="" scope="task"
    timestampfield=""/>

  </task>

  
  <!-- ##############################################################################-->  

  <task title="Pagos de las operadoras en revisado" id="Pago_Revisado">
   <port side="forward" type="split">
    
 <connection query="select operadora_declaracion.pagado from operadora_operadora" options="true"
       source="Pago_Pago" tokenlink="[usuario_operadora_id,operadora_id:operadora_declaracion]"/>

          
   </port>
   <variable config="1" documentsource="select razon_social, operadora_recaudacion.id,operadora_recaudacion.anho, operadora_recaudacion.num_periodo, operadora_declaracion.recaudacion_id, operadora_declaracion.id, operadora_detallepago.declaracion_id, operadora_detallepago.id,  operadora_pago.id, operadora_pago.estatus_pago_id from operadora_operadora" type="sql" 
    tokenlink="[usuario_operadora_id,operadora_id:operadora_declaracion][recaudacion_id,id:operadora_recaudacion][id,declaracion_id:operadora_detallepago][pago_id,id:operadora_pago]" 
    id="vPago_Revisado" rolfield="" scope="task"
    timestampfield=""/>

  </task>
  
  
<!-- ##############################################################################-->  


  <task title="Operadoras que han pagado" id="Pago_Pago">
   <port side="forward" type="split">
    
        <connection query="true" options="" source="final"/>     

   </port>
   <variable config="1" documentsource="select razon_social from operadora_operadora" type="sql" 
    tokenlink="[usuario_operadora_id,operadora_id:operadora_declaracion]" 
    id="vPago_Pago" rolfield="" scope="task"
    timestampfield=""/>

  </task>




<!-- ##############################################################################-->  


  <condition id="final">
   <port side="forward" type="split">
    <connection source=""/>
   </port>
  </condition>
  


 </workflow>
 <configuration id="1" connectstring="psql:seguridad.cenditel.gob.ve:ticket:vbravo:vbravo_"/>
</yawl>

=== victorrbravo/gestioninterna/gestioninterna/.safet/flowfiles/ReportePorEstadoSinConvenio.xml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE yawl SYSTEM 'file:///home/c30/.safet/dtd/yawlworkflow.dtd'>
<!--
Documento  : ConvenioOperadora.xml
Creado     : 27/10/2015 09:27 AM
Autor      : Josè Sulbaràn
Descripcion: Archivo generado por plantilla de la Libreria SAFET
-->


<yawl version="0.01">
 <workflow id="operadora_declaracion">
<token keysource="operadora_recaudacion" key="anho"/>
 
<parameter title="Anho"  type="string" mandatory="si"/>
<parameter title="Periodo"  type="string" mandatory="si"/>
<parameter title="Convenio"  type="string" mandatory="si"/>
  <!-- ################################################# -->

  <condition type="start" id="inicial">
   <port side="forward" type="split">
   <connection query=" select anho from operadora_recaudacion" options="{#Anho}" source="Anho"
      tokenlink=""/>
   </port>
  </condition>
  

  <!-- ################################################ -->

  <task title="" id="Anho"> 
   <port side="forward" type="split">
    
   
    <connection query=" select num_periodo from operadora_recaudacion" options="{#Periodo}" source="Trimestre"
      tokenlink=""/>


   </port>

  <variable config="1" documentsource="select anho from operadora_recaudacion" 
    type="sql" tokenlink=""  id="vAnho" rolfield="" scope="task" timestampfield=""/>
  </task>




  <!-- ################################################ -->

  <task title="" id="Trimestre"> 
   <port side="forward" type="split">
    
   
    <connection query=" select pagado from operadora_recaudacion" options="{#Convenio}" source="Convenios"
      tokenlink="[id,recaudacion_id:operadora_declaracion]"/>

   </port>

  <variable config="1" documentsource="select  num_periodo from operadora_recaudacion" 
    type="sql" tokenlink=""  id="vTrimestre" rolfield="" scope="task" timestampfield=""/>
  </task>


  <!-- ################################################ -->

  <task title="Activo/Desactivo" id="Convenios"> 
   <port side="forward" type="split">
    
   
      <connection query="select operadora_pago.id from operadora_recaudacion" options=">0"
       source="DataPorEstadoSinConvenio" tokenlink="[id,recaudacion_id:operadora_declaracion][id,declaracion_id:operadora_detallepago][pago_id,id:operadora_pago][operadora_declaracion.operadora_id,usuario_operadora_id:operadora_operadora]
       "/>
 

   </port>

  <variable config="1" documentsource="select  num_periodo, pagado, operadora_declaracion.convenio_id from operadora_recaudacion" 
    type="sql" tokenlink="[id,recaudacion_id:operadora_declaracion]"  id="vConvenios" rolfield="" scope="task" timestampfield=""/>
  </task>


<!-- ################################################## -->

  <task title="" id="DataPorEstadoSinConvenio"> 
   <port side="forward" type="split">
    
   <connection query="true" options="" source="final"/>
     
   </port>

  <variable config="1" documentsource="select distinct operadora_id, razon_social,rif, fecha_pago, convenio_id, operadora_declaracion.id, operadora_declaracion.pagado from operadora_recaudacion" type="sql" 
    tokenlink="[id,recaudacion_id:operadora_declaracion][id,declaracion_id:operadora_detallepago][pago_id,id:operadora_pago][operadora_declaracion.operadora_id,usuario_operadora_id:operadora_operadora]
       " 
    id="vDataPorEstadoSinConvenio" rolfield="" scope="task"
    timestampfield="" groupby= "order by fecha_pago DESC "/>
  </task>

  <!-- ################################################ -->

  <condition id="final">
   <port side="forward" type="split">
    <connection source=""/>
   </port>
  </condition>

  
 </workflow>
 <configuration id="1" connectstring="psql:seguridad.cenditel.gob.ve:ticket:vbravo:vbravo_"/>
</yawl>

=== victorrbravo/gestioninterna/gestioninterna/.safet/flowfiles/SolicitudVistaVacacionessp.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--
Documento  : tickets.xml
Creado     : 16/10/08 09:27 AM
Autor      : nombre_autor
Descripcion: Archivo generado por plantilla de la Libreria SAFET
-->

<!--<!DOCTYPE yawl SYSTEM "http://trac-safet.cenditel.gob.ve/dtd/yawlworkflow.dtd">-->
<!DOCTYPE yawl SYSTEM "file:///home/vbravo/.safet/dtd/yawlworkflow.dtd">
<yawl  version="0.01">
<workflow id="Generar planilla de solicitud de vista_vacaciones" desc="Planilla que se generar con los datos de una solicitud de vista_vacaciones">
<token key="id"  keysource="vista_vacaciones">
</token>

    
<condition id="inicial" type="start">
	<port side="forward" type="split"  >
		<connection   source="Iniciado" query="select status from vista_vacaciones"  options="iniciado" tokenlink="" >
		</connection>
	</port>
</condition>

<task id="Iniciado"  title="todas" >
	<port side="forward" type="split"  >
		<connection   source="TalentoHumano" query="select status from vista_vacaciones"  options="TalentoHumano" tokenlink="" >
		</connection>

	</port>
	 <variable id="vSolicitud" scope="task"  type="sql" config="1"   tokenlink="" 
                documentsource="select id_cedula from vista_vacaciones"
 

 >
     </variable>
</task>
<task id="TalentoHumano"  title="todas" >
	<port side="forward" type="split"  >
		<connection   source="Direccion" query="select status from vista_vacaciones"  options="Direccion" tokenlink="" >
		</connection>

	</port>
	 <variable id="vTalentoHumano" scope="task"  type="sql" config="1"   tokenlink="" 
                documentsource="select id_cedula from vista_vacaciones"
rolfield="(select nombre_periodo from vacaciones_registro where vacaciones_registro.id_vacaciones=vista_vacaciones.id and vacaciones_registro.status='TalentoHumano' limit 1)"  timestampfield="(select fecha_accion from vacaciones_registro where vacaciones_registro.id_vacaciones=vista_vacaciones.id and vacaciones_registro.status='TalentoHumano' limit 1)" 

 >
     </variable>
</task>

<task id="Direccion"  title="Planilla vista_vacaciones" >
	<port side="forward" type="split"  >
	    <connection source="Presidencia" query="select status from vista_vacaciones" options="Presidencia" >
        </connection>
	</port>
	 <variable id="vDireccion" scope="task"  type="sql" config="1"   tokenlink=""
                 documentsource="select id_cedula from vista_vacaciones"
 rolfield=""  timestampfield="" 


 >
     </variable>
</task>
<task id="Presidencia"  title="Aprobacion del Presidente" >
	<port side="forward" type="split" pattern="none" >
		<connection source="Archivar_solicitud_procesada" query="select status from vista_vacaciones" options="Archivar_solicitud_procesada" tokenlink="" >

		</connection>
	</port>
	 <variable id="vPresidencia" scope="task"  type="sql" config="1"   tokenlink=""
                 documentsource="select id_cedula, nombreapellido from vista_vacaciones"
 rolfield=""  timestampfield="" 

 >
     </variable>
</task>
<task id="Archivar_solicitud_procesada"  title="solicitud_archivada" >
	<port side="forward" type="split"  >
		<connection source="final" query="true" options="" tokenlink="" >

		</connection>

	</port>
	 <variable id="vArchivar" scope="task"  type="sql" config="1"   tokenlink=""
                 documentsource="select id_cedula, nombreapellido, diasadisfrutar, diasdisfrutados, diassolicitados, diaspordisfrutar, fechasolicitud, fechainicio, fechafin, suplenteinterno_1, suplenteinterno_2, cedula_suplente_1, cedula_suplente_2, vista_vacaciones.cargo, vista_vacaciones.fecha_ingreso, nombre, vista_vacaciones.departamento, cargo_1, cargo_2, vista_vacaciones.fechaincorporacion, fechafin, diasinhabiles, diasadicionales, bonoacancelar, sueldodelmes, sueldoanticipado, totalapagar, observaciones_talento_humano, observaciones_direccion_ejecutiva, observaciones_presidencia from vista_vacaciones"
 rolfield=""  timestampfield="" 
 >
     </variable>
</task>
<condition id="final">
	<port side="forward" type="split">
		<connection source="">
		</connection>
	</port>
</condition>
</workflow>
	<configuration id="1" connectstring="psql:seguridad.cenditel.gob.ve:ticket:vbravo:vbravo_">
	</configuration>
</yawl>

=== victorrbravo/gestioninterna/gestioninterna/.safet/flowfiles/ConvenioOperadoraRif.xml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE yawl SYSTEM 'file:///home/c30/.safet/dtd/yawlworkflow.dtd'>
<!--
Documento  : ConvenioOperadora.xml
Creado     : 27/10/2015 09:27 AM
Autor      : Josè Sulbaràn
Descripcion: Archivo generado por plantilla de la Libreria SAFET
-->


<yawl version="0.01">
 <workflow id="operadora_recaudacion">
<token keysource="operadora_operadora" key="usuario_operadora_id"/>
 
<parameter title="Rif"  type="string" mandatory="si"/>

  <!-- ################################################# -->

  <condition type="start" id="inicial">
   <port side="forward" type="split">
   <connection query=" select usuario_operadora_id from operadora_operadora" options=">0" source="Operadoras"
      tokenlink=""/>
   </port>
  </condition>
  

<!-- ##############################################################################-->  


  <task title="Generales" id="Operadoras">
   <port side="forward" type="split">
    
    <connection
       query="select rif from operadora_operadora" options="{#Rif}"  source="Rif_De_Busqueda"
       tokenlink=""/>
       
   </port>

   <variable config="1" documentsource="select razon_social from operadora_operadora" type="sql" 
    tokenlink="" 
    id="vOperadoras" rolfield="" scope="task"
    timestampfield=""/>

  </task>


  <!-- ################################################ -->

  <task title="{#Rif}" id="Rif_De_Busqueda"> 
   <port side="forward" type="split" >
  

        <connection query="select operadora_declaracion.convenio_id from operadora_operadora" options=">0"
       source="Convenio" tokenlink="[usuario_operadora_id,operadora_id:operadora_declaracion]"/>

     
   </port>

  <variable config="1" documentsource="select usuario_operadora_id from operadora_operadora " 
    type="sql" tokenlink=""  id="vRif_De_Busqueda" rolfield="" scope="task" timestampfield=""/>
  </task>

<!-- ################################################### -->

  <task title="Convenios que a realizado la operadora" id="Convenio"> 
   <port side="forward" type="split" pattern="or">
  

        <connection query="select operadora_convenio.pagado from operadora_operadora" options="true"
       source="Desactivo" tokenlink="[usuario_operadora_id,operadora_id:operadora_declaracion][convenio_id,id:operadora_convenio]"/>
 
         
     <connection query="select  operadora_convenio.pagado from operadora_operadora" options="false"
       source="Activo" tokenlink="[usuario_operadora_id,operadora_id:operadora_declaracion][convenio_id,id:operadora_convenio][id,convenio_id:operadora_pagoconvenio]"/>


     
   </port>

  <variable config="1" documentsource="select distinct operadora_declaracion.convenio_id from operadora_operadora " 
    type="sql" tokenlink="[usuario_operadora_id,operadora_id:operadora_declaracion]" 
     id="vConvenio" rolfield="" scope="task" timestampfield=""/>
  </task>

 <!-- ################################################### -->

  <task title="Operadora tiene convenio activo" id="Activo"> 
   <port side="forward" type="split" >
    
      <connection query="select operadora_pagoconvenio.convenio_id from operadora_operadora" options=">0"
       source="Cuotas" tokenlink="[usuario_operadora_id,operadora_id:operadora_declaracion][convenio_id,id:operadora_convenio][id,convenio_id:operadora_pagoconvenio]"/>
     
   
   </port>
  <variable config="1" documentsource="select distinct operadora_declaracion.convenio_id, operadora_convenio.pagado from operadora_operadora " type="sql" 
    tokenlink="[usuario_operadora_id,operadora_id:operadora_declaracion][convenio_id,id:operadora_convenio][id,convenio_id:operadora_pagoconvenio]" 
    id="vActivo" rolfield="" scope="task"
    timestampfield=""/>
  </task>

 
<!-- ################################################## -->

  <task title="Total de cuotas a pagar" id="Cuotas"> 
   <port side="forward" type="split" >
    
       <connection query="true" options="" source="final"/>
   </port>

  <variable config="1" documentsource="select operadora_pagoconvenio.convenio_id from operadora_operadora" type="sql" 
    tokenlink="[usuario_operadora_id,operadora_id:operadora_declaracion][convenio_id,id:operadora_convenio][id,convenio_id:operadora_pagoconvenio]" 
    id="vCuotas" rolfield="" scope="task"
    timestampfield=""/>
  </task>
  
  <!--   ####################################################  -->
  
<task title="Operadora tiene convenios desactivos" id="Desactivo"> 
   <port side="forward" type="split" >
      <connection query="true" options="" source="final"/>
   </port>
  <variable config="1" documentsource="select operadora_declaracion.id, operadora_declaracion.convenio_id, operadora_convenio.pagado from operadora_operadora " type="sql" 
    tokenlink="[usuario_operadora_id,operadora_id:operadora_declaracion][convenio_id,id:operadora_convenio]" 
    id="vDesactivo" rolfield="" scope="task"
    timestampfield=""/>
  </task>

  

  <condition id="final">
   <port side="forward" type="split">
    <connection source=""/>
   </port>
  </condition>
  
 </workflow>
 <configuration id="1" connectstring="psql:seguridad.cenditel.gob.ve:ticket:vbravo:vbravo_"/>
</yawl>
